package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccountType generated by hbm2java
 */
@Entity
@Table(name = "account_type")
public class AccountType implements java.io.Serializable {

	private Long accountTypeId;
	private String accountName;
	private String description;
	private Set<Resturant> resturants = new HashSet<Resturant>(0);

	public AccountType() {
	}

	public AccountType(String accountName, String description,
			Set<Resturant> resturants) {
		this.accountName = accountName;
		this.description = description;
		this.resturants = resturants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACCOUNT_TYPE_ID", unique = true, nullable = false)
	public Long getAccountTypeId() {
		return this.accountTypeId;
	}

	public void setAccountTypeId(Long accountTypeId) {
		this.accountTypeId = accountTypeId;
	}

	@Column(name = "ACCOUNT_NAME")
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountType")
	public Set<Resturant> getResturants() {
		return this.resturants;
	}

	public void setResturants(Set<Resturant> resturants) {
		this.resturants = resturants;
	}

}
