package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddonTranslation generated by hbm2java
 */
@Entity
@Table(name = "addon_translation")
public class AddonTranslation implements java.io.Serializable {

	private Long addonTrnaslationId;
	private RefLanguages refLanguages;
	private String title;
	private String description;
	private Integer showDescription;

	private Addons addon;
	
	public AddonTranslation() {
	}

	public AddonTranslation(RefLanguages refLanguages, String title) {
		this.refLanguages = refLanguages;
		this.title = title;
	}

	public AddonTranslation(RefLanguages refLanguages, String title,
			String description, Integer showDescription) {
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ADDON_TRNASLATION_ID", unique = true, nullable = false)
	public Long getAddonTrnaslationId() {
		return this.addonTrnaslationId;
	}

	public void setAddonTrnaslationId(Long addonTrnaslationId) {
		this.addonTrnaslationId = addonTrnaslationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addon_id", nullable = false)
	public Addons getAddon() {
		return addon;
	}
	
	public void setAddon(Addons addon) {
		this.addon = addon;
	}
}
