package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Addons generated by hbm2java
 */
@Entity
@Table(name = "addons")
public class Addons implements java.io.Serializable {

	private Long addonId;
	private Resturant resturant;
	private Integer isActive;
	private BigDecimal price;
	private String imageUrl;
	private Set<ItemAddon> itemAddons = new HashSet<ItemAddon>(0);
	private Set<AddonTranslation> addonTranslations = new HashSet<AddonTranslation>(
			0);
	
	public Addons() {
	}

	public Addons(Resturant resturant, BigDecimal price) {
		this.resturant = resturant;
		this.price = price;
	}
	

	public Addons(Resturant resturant, Integer isActive, BigDecimal price,
			String imageUrl, Set<ItemAddon> itemAddons) {
		this.resturant = resturant;
		this.isActive = isActive;
		this.price = price;
		this.imageUrl = imageUrl;
		this.itemAddons = itemAddons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ADDON_ID", unique = true, nullable = false)
	public Long getAddonId() {
		return this.addonId;
	}

	public void setAddonId(Long addonId) {
		this.addonId = addonId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "IMAGE_URL")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addons")
	public Set<ItemAddon> getItemAddons() {
		return this.itemAddons;
	}

	public void setItemAddons(Set<ItemAddon> itemAddons) {
		this.itemAddons = itemAddons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addon")
	public Set<AddonTranslation> getAddonTranslations() {
		return addonTranslations;
	}
	
	public void setAddonTranslations(Set<AddonTranslation> addonTranslations) {
		this.addonTranslations = addonTranslations;
	}
}
