package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch")
public class Branch implements java.io.Serializable {

	private Long branchId;
	private Resturant resturant;
	private Address address;
	private long managerId;
	private Integer isActive;
	private Set<Staff> staffs = new HashSet<Staff>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<ServingTable> servingTables = new HashSet<ServingTable>(0);
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

	public Branch() {
	}

	public Branch(Resturant resturant, Address address, long managerId) {
		this.resturant = resturant;
		this.address = address;
		this.managerId = managerId;
	}

	public Branch(Resturant resturant, Address address, long managerId,
			Integer isActive, Set<Staff> staffs, Set<Orders> orderses,
			Set<ServingTable> servingTables, Set<Feedback> feedbacks) {
		this.resturant = resturant;
		this.address = address;
		this.managerId = managerId;
		this.isActive = isActive;
		this.staffs = staffs;
		this.orderses = orderses;
		this.servingTables = servingTables;
		this.feedbacks = feedbacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BRANCH_ID", unique = true, nullable = false)
	public Long getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Long branchId) {
		this.branchId = branchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_ID", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "MANAGER_ID", nullable = false)
	public long getManagerId() {
		return this.managerId;
	}

	public void setManagerId(long managerId) {
		this.managerId = managerId;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<ServingTable> getServingTables() {
		return this.servingTables;
	}

	public void setServingTables(Set<ServingTable> servingTables) {
		this.servingTables = servingTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

}
