package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CuisineTranslation generated by hbm2java
 */
@Entity
@Table(name = "cuisine_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CUISINE_TYPE_ID", "LANGUAGE_ID" }))
public class CuisineTranslation implements java.io.Serializable {

	private Long cuisineTransId;
	private RefLanguages refLanguages;
	private CuisineType cuisineType;
	private String title;
	private String description;
	private Integer showDescription;

	public CuisineTranslation() {
	}

	public CuisineTranslation(RefLanguages refLanguages,
			CuisineType cuisineType, String title, String description) {
		this.refLanguages = refLanguages;
		this.cuisineType = cuisineType;
		this.title = title;
		this.description = description;
	}

	public CuisineTranslation(RefLanguages refLanguages,
			CuisineType cuisineType, String title, String description,
			Integer showDescription) {
		this.refLanguages = refLanguages;
		this.cuisineType = cuisineType;
		this.title = title;
		this.description = description;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUISINE_TRANS_ID", unique = true, nullable = false)
	public Long getCuisineTransId() {
		return this.cuisineTransId;
	}

	public void setCuisineTransId(Long cuisineTransId) {
		this.cuisineTransId = cuisineTransId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUISINE_TYPE_ID", nullable = false)
	public CuisineType getCuisineType() {
		return this.cuisineType;
	}

	public void setCuisineType(CuisineType cuisineType) {
		this.cuisineType = cuisineType;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

}
