package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CuisineType generated by hbm2java
 */
@Entity
@Table(name = "cuisine_type")
public class CuisineType implements java.io.Serializable {

	private Long cuisineTypeId;
	private Resturant resturant;
	private String imageUrl;
	private Integer isActive;
	private String title;
	private Set<Item> items = new HashSet<Item>(0);
	private Set<CuisineTranslation> cuisineTranslations = new HashSet<CuisineTranslation>(
			0);

	public CuisineType() {
	}

	public CuisineType(Resturant resturant, String imageUrl) {
		this.resturant = resturant;
		this.imageUrl = imageUrl;
	}

	public CuisineType(Resturant resturant, String imageUrl, Integer isActive,
			String title, Set<Item> items,
			Set<CuisineTranslation> cuisineTranslations) {
		this.resturant = resturant;
		this.imageUrl = imageUrl;
		this.isActive = isActive;
		this.title = title;
		this.items = items;
		this.cuisineTranslations = cuisineTranslations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUISINE_TYPE_ID", unique = true, nullable = false)
	public Long getCuisineTypeId() {
		return this.cuisineTypeId;
	}

	public void setCuisineTypeId(Long cuisineTypeId) {
		this.cuisineTypeId = cuisineTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "IMAGE_URL", nullable = false)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuisineType")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuisineType")
	public Set<CuisineTranslation> getCuisineTranslations() {
		return this.cuisineTranslations;
	}

	public void setCuisineTranslations(
			Set<CuisineTranslation> cuisineTranslations) {
		this.cuisineTranslations = cuisineTranslations;
	}

}
