package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", uniqueConstraints = @UniqueConstraint(columnNames = "CODE"))
public class Customer implements java.io.Serializable {

	private Long customerId;
	private Resturant resturant;
	private String code;
	private String firstName;
	private String lastName;
	private String mobile;
	private Long addressId;
	private Integer subscribeNewsLetter;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Customer() {
	}

	public Customer(Resturant resturant, String code, String firstName) {
		this.resturant = resturant;
		this.code = code;
		this.firstName = firstName;
	}

	public Customer(Resturant resturant, String code, String firstName,
			String lastName, String mobile, Long addressId,
			Integer subscribeNewsLetter, Set<Orders> orderses) {
		this.resturant = resturant;
		this.code = code;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobile = mobile;
		this.addressId = addressId;
		this.subscribeNewsLetter = subscribeNewsLetter;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false)
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "CODE", unique = true, nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "FIRST_NAME", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MOBILE", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ADDRESS_ID")
	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	@Column(name = "SUBSCRIBE_NEWS_LETTER")
	public Integer getSubscribeNewsLetter() {
		return this.subscribeNewsLetter;
	}

	public void setSubscribeNewsLetter(Integer subscribeNewsLetter) {
		this.subscribeNewsLetter = subscribeNewsLetter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
