package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeedbackType generated by hbm2java
 */
@Entity
@Table(name = "feedback_type")
public class FeedbackType implements java.io.Serializable {

	private Long feedbackTypeId;
	private Integer isActive;
	private long resturantId;
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

	public FeedbackType() {
	}

	public FeedbackType(long resturantId) {
		this.resturantId = resturantId;
	}

	public FeedbackType(Integer isActive, long resturantId,
			Set<Feedback> feedbacks) {
		this.isActive = isActive;
		this.resturantId = resturantId;
		this.feedbacks = feedbacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FEEDBACK_TYPE_ID", unique = true, nullable = false)
	public Long getFeedbackTypeId() {
		return this.feedbackTypeId;
	}

	public void setFeedbackTypeId(Long feedbackTypeId) {
		this.feedbackTypeId = feedbackTypeId;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "RESTURANT_ID", nullable = false)
	public long getResturantId() {
		return this.resturantId;
	}

	public void setResturantId(long resturantId) {
		this.resturantId = resturantId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedbackType")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

}
