package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback")
public class Feedback implements java.io.Serializable {

	private Long feedbackId;
	private Branch branch;
	private FeedbackType feedbackType;
	private Orders orders;
	private int rating;
	private String remarks;
	private Set<FeedbackTranslation> feedbackTranslations = new HashSet<FeedbackTranslation>(
			0);

	public Feedback() {
	}

	public Feedback(Branch branch, FeedbackType feedbackType, Orders orders,
			int rating) {
		this.branch = branch;
		this.feedbackType = feedbackType;
		this.orders = orders;
		this.rating = rating;
	}

	public Feedback(Branch branch, FeedbackType feedbackType, Orders orders,
			int rating, String remarks,
			Set<FeedbackTranslation> feedbackTranslations) {
		this.branch = branch;
		this.feedbackType = feedbackType;
		this.orders = orders;
		this.rating = rating;
		this.remarks = remarks;
		this.feedbackTranslations = feedbackTranslations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FEEDBACK_ID", unique = true, nullable = false)
	public Long getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(Long feedbackId) {
		this.feedbackId = feedbackId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRANCH_ID", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FEEDBACK_TYPE_ID", nullable = false)
	public FeedbackType getFeedbackType() {
		return this.feedbackType;
	}

	public void setFeedbackType(FeedbackType feedbackType) {
		this.feedbackType = feedbackType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "RATING", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedback")
	public Set<FeedbackTranslation> getFeedbackTranslations() {
		return this.feedbackTranslations;
	}

	public void setFeedbackTranslations(
			Set<FeedbackTranslation> feedbackTranslations) {
		this.feedbackTranslations = feedbackTranslations;
	}

}
