package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FeedbackTranslation generated by hbm2java
 */
@Entity
@Table(name = "feedback_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"FEEDBACK_TYPE_ID", "LANGUAGE_ID" }))
public class FeedbackTranslation implements java.io.Serializable {

	private Long feedbackTransId;
	private Feedback feedback;
	private RefLanguages refLanguages;
	private String title;
	private String description;
	private Integer showDescription;

	public FeedbackTranslation() {
	}

	public FeedbackTranslation(Feedback feedback, RefLanguages refLanguages,
			String title) {
		this.feedback = feedback;
		this.refLanguages = refLanguages;
		this.title = title;
	}

	public FeedbackTranslation(Feedback feedback, RefLanguages refLanguages,
			String title, String description, Integer showDescription) {
		this.feedback = feedback;
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FEEDBACK_TRANS_ID", unique = true, nullable = false)
	public Long getFeedbackTransId() {
		return this.feedbackTransId;
	}

	public void setFeedbackTransId(Long feedbackTransId) {
		this.feedbackTransId = feedbackTransId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FEEDBACK_TYPE_ID", nullable = false)
	public Feedback getFeedback() {
		return this.feedback;
	}

	public void setFeedback(Feedback feedback) {
		this.feedback = feedback;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

}
