package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IngredientTranslation generated by hbm2java
 */
@Entity
@Table(name = "ingredient_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"INGREDIENT_ID", "LANGUAGE_ID" }))
public class IngredientTranslation implements java.io.Serializable {

	private Long ingredientTransId;
	private RefLanguages refLanguages;
	private Ingredients ingredients;
	private String description;
	private String title;
	private Integer showDescription;

	public IngredientTranslation() {
	}

	public IngredientTranslation(RefLanguages refLanguages,
			Ingredients ingredients, String title) {
		this.refLanguages = refLanguages;
		this.ingredients = ingredients;
		this.title = title;
	}

	public IngredientTranslation(RefLanguages refLanguages,
			Ingredients ingredients, String description, String title,
			Integer showDescription) {
		this.refLanguages = refLanguages;
		this.ingredients = ingredients;
		this.description = description;
		this.title = title;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INGREDIENT_TRANS_ID", unique = true, nullable = false)
	public Long getIngredientTransId() {
		return this.ingredientTransId;
	}

	public void setIngredientTransId(Long ingredientTransId) {
		this.ingredientTransId = ingredientTransId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INGREDIENT_ID", nullable = false)
	public Ingredients getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Ingredients ingredients) {
		this.ingredients = ingredients;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

}
