package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ingredients generated by hbm2java
 */
@Entity
@Table(name = "ingredients")
public class Ingredients implements java.io.Serializable {

	private Long ingredientId;
	private Resturant resturant;
	private String imageUrl;
	private Integer isActive;
	private Set<IngredientTranslation> ingredientTranslations = new HashSet<IngredientTranslation>(
			0);
	private Set<ItemIngredient> itemIngredients = new HashSet<ItemIngredient>(0);

	public Ingredients() {
	}

	public Ingredients(Resturant resturant, String imageUrl) {
		this.resturant = resturant;
		this.imageUrl = imageUrl;
	}

	public Ingredients(Resturant resturant, String imageUrl, Integer isActive,
			Set<IngredientTranslation> ingredientTranslations,
			Set<ItemIngredient> itemIngredients) {
		this.resturant = resturant;
		this.imageUrl = imageUrl;
		this.isActive = isActive;
		this.ingredientTranslations = ingredientTranslations;
		this.itemIngredients = itemIngredients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INGREDIENT_ID", unique = true, nullable = false)
	public Long getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(Long ingredientId) {
		this.ingredientId = ingredientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "IMAGE_URL", nullable = false)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<IngredientTranslation> getIngredientTranslations() {
		return this.ingredientTranslations;
	}

	public void setIngredientTranslations(
			Set<IngredientTranslation> ingredientTranslations) {
		this.ingredientTranslations = ingredientTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<ItemIngredient> getItemIngredients() {
		return this.itemIngredients;
	}

	public void setItemIngredients(Set<ItemIngredient> itemIngredients) {
		this.itemIngredients = itemIngredients;
	}

}
