package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import static com.icarte.commons.Constants.NamedQueries.FIND_CATEGORIES_TRANS_BY_MENU_ID;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * ItemCategoryTranslation generated by hbm2java
 */
@Entity
@Table(name = "item_category_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"LANGUAGE_ID", "MENU_CATEGORY_ID" }))
@NamedQueries({ @NamedQuery(name = FIND_CATEGORIES_TRANS_BY_MENU_ID, query = "from ItemCategoryTranslation categoryTranslation inner join fetch categoryTranslation.itemCategory itemCategory inner join fetch itemCategory.menu menu inner join fetch categoryTranslation.refLanguages lang inner join fetch menu.resturant rest where menu.menuId = :menuId and lang.languageId = :lang") })
public class ItemCategoryTranslation implements java.io.Serializable {

	private Long itemCategoryTransId;
	private RefLanguages refLanguages;
	private ItemCategory itemCategory;
	private String title;
	private String description;
	private Integer showDescription;

	public ItemCategoryTranslation() {
	}

	public ItemCategoryTranslation(RefLanguages refLanguages,
			ItemCategory itemCategory) {
		this.refLanguages = refLanguages;
		this.itemCategory = itemCategory;
	}

	public ItemCategoryTranslation(RefLanguages refLanguages,
			ItemCategory itemCategory, String title, String description,
			Integer showDescription) {
		this.refLanguages = refLanguages;
		this.itemCategory = itemCategory;
		this.title = title;
		this.description = description;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_CATEGORY_TRANS_ID", unique = true, nullable = false)
	public Long getItemCategoryTransId() {
		return this.itemCategoryTransId;
	}

	public void setItemCategoryTransId(Long itemCategoryTransId) {
		this.itemCategoryTransId = itemCategoryTransId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_CATEGORY_ID", nullable = false)
	public ItemCategory getItemCategory() {
		return this.itemCategory;
	}

	public void setItemCategory(ItemCategory itemCategory) {
		this.itemCategory = itemCategory;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

//	@Transient
//	public String toString(){
//		StringBuilder objectJSON = new StringBuilder("{")
//		.append("\"itemCategoryTransId\" : ").append(itemCategoryTransId).append(",")
//		.append("\"refLanguages\" : ").append(refLanguages.getLanguageId()).append(",")
//		.append("\"title\" : \"").append(title).append("\",")
//		.append("\"description\" : \"").append(description).append("\",")
//		.append("\"showDescription\" : ").append(showDescription).append(",")
//		.append("\"itemCategory\" : ")
//		.append(itemCategory.toString())
//		.append("}");
//		return objectJSON.toString();
//	}
	
	
}
