package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

import static com.icarte.commons.Constants.NamedQueries.*;
/**
 * Item generated by hbm2java
 */
@NamedQueries({
	@NamedQuery(name = FIND_ITEMS_BY_CATEGORY , query = "from Item item inner join fetch item.itemTranslations itemTrans inner join fetch itemTrans.refLanguages langs  inner join fetch item.itemCategory itemCategory where itemCategory.itemCategoryId = :categoryId")	
})



@Entity
@Table(name = "item", uniqueConstraints = @UniqueConstraint(columnNames = {"ITEM_CATEGORY_ID", "CUISINE_TYPE_ID", "SPICE_TYPE_ID" }))
public class Item implements java.io.Serializable {

	private Long itemId;
	private SpiceType spiceType;
	private ItemCategory itemCategory;
	private CuisineType cuisineType;
	private BigDecimal price;
	private String tags;
	private Set<ItemMediaContent> itemMediaContents = new HashSet<ItemMediaContent>(
			0);
	private Set<ItemTranslation> itemTranslations = new HashSet<ItemTranslation>(
			0);
	private Set<ItemIngredient> itemIngredients = new HashSet<ItemIngredient>(0);
	private Set<ItemAddon> itemAddons = new HashSet<ItemAddon>(0);
	private Set<SpecialDealItem> specialDealItems = new HashSet<SpecialDealItem>(
			0);
	
	private Set<ItemVariant> itemVariants = new HashSet<ItemVariant>();
	
	
	
	public Item() {
	}

	public Item(SpiceType spiceType, ItemCategory itemCategory,
			CuisineType cuisineType, BigDecimal price) {
		this.spiceType = spiceType;
		this.itemCategory = itemCategory;
		this.cuisineType = cuisineType;
		this.price = price;
	}

	public Item(SpiceType spiceType, ItemCategory itemCategory,
			CuisineType cuisineType, BigDecimal price, String tags,
			Set<ItemMediaContent> itemMediaContents,
			Set<ItemTranslation> itemTranslations,
			Set<ItemIngredient> itemIngredients, Set<ItemAddon> itemAddons,
			Set<SpecialDealItem> specialDealItems) {
		this.spiceType = spiceType;
		this.itemCategory = itemCategory;
		this.cuisineType = cuisineType;
		this.price = price;
		this.tags = tags;
		this.itemMediaContents = itemMediaContents;
		this.itemTranslations = itemTranslations;
		this.itemIngredients = itemIngredients;
		this.itemAddons = itemAddons;
		this.specialDealItems = specialDealItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_ID", unique = true, nullable = false)
	public Long getItemId() {
		return this.itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPICE_TYPE_ID", nullable = false)
	public SpiceType getSpiceType() {
		return this.spiceType;
	}

	public void setSpiceType(SpiceType spiceType) {
		this.spiceType = spiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_CATEGORY_ID", nullable = false)
	public ItemCategory getItemCategory() {
		return this.itemCategory;
	}

	public void setItemCategory(ItemCategory itemCategory) {
		this.itemCategory = itemCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUISINE_TYPE_ID", nullable = false)
	public CuisineType getCuisineType() {
		return this.cuisineType;
	}

	public void setCuisineType(CuisineType cuisineType) {
		this.cuisineType = cuisineType;
	}

	@Column(name = "PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "TAGS", length = 500)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemMediaContent> getItemMediaContents() {
		return this.itemMediaContents;
	}

	public void setItemMediaContents(Set<ItemMediaContent> itemMediaContents) {
		this.itemMediaContents = itemMediaContents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemTranslation> getItemTranslations() {
		return this.itemTranslations;
	}

	public void setItemTranslations(Set<ItemTranslation> itemTranslations) {
		this.itemTranslations = itemTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemIngredient> getItemIngredients() {
		return this.itemIngredients;
	}

	public void setItemIngredients(Set<ItemIngredient> itemIngredients) {
		this.itemIngredients = itemIngredients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemAddon> getItemAddons() {
		return this.itemAddons;
	}

	public void setItemAddons(Set<ItemAddon> itemAddons) {
		this.itemAddons = itemAddons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<SpecialDealItem> getSpecialDealItems() {
		return this.specialDealItems;
	}

	public void setSpecialDealItems(Set<SpecialDealItem> specialDealItems) {
		this.specialDealItems = specialDealItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemVariant> getItemVariants() {
		return itemVariants;
	}
	
	public void setItemVariants(Set<ItemVariant> itemVariants) {
		this.itemVariants = itemVariants;
	}
	

}
