package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;
import static com.icarte.commons.Constants.NamedQueries.*;

/**
 * ItemTranslation generated by hbm2java
 */

@NamedQueries({ @NamedQuery(name = FIND_ITEM_TRANS_BY_CATEGORY_ID, query = "from ItemTranslation itemTrans inner join fetch itemTrans.item item inner join fetch itemTrans.refLanguages langs  inner join fetch item.itemCategory itemCategory inner join fetch item.spiceType spiceType inner join fetch item.cuisineType cuisineType  where itemCategory.itemCategoryId = :categoryId and langs.languageId = :langId") })
@Entity
@Table(name = "item_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEM_ID", "LANGUAGE_ID" }))
public class ItemTranslation implements java.io.Serializable {

	private Long itemTranslationId;
	private RefLanguages refLanguages;
	private Item item;
	private String title;
	private String description;
	private String dietaryInformation;
	private Integer isSpicy;
	private Integer showDescription;

	@Transient
	public String toString() {
		StringBuilder jsonData = new StringBuilder("{")

		.append("}");
		return jsonData.toString();
	}

	public ItemTranslation() {
	}

	public ItemTranslation(RefLanguages refLanguages, Item item, String title,
			String description) {
		this.refLanguages = refLanguages;
		this.item = item;
		this.title = title;
		this.description = description;
	}

	public ItemTranslation(RefLanguages refLanguages, Item item, String title,
			String description, String dietaryInformation, Integer isSpicy,
			Integer showDescription) {
		this.refLanguages = refLanguages;
		this.item = item;
		this.title = title;
		this.description = description;
		this.dietaryInformation = dietaryInformation;
		this.isSpicy = isSpicy;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_TRANSLATION_ID", unique = true, nullable = false)
	public Long getItemTranslationId() {
		return this.itemTranslationId;
	}

	public void setItemTranslationId(Long itemTranslationId) {
		this.itemTranslationId = itemTranslationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DIETARY_INFORMATION")
	public String getDietaryInformation() {
		return this.dietaryInformation;
	}

	public void setDietaryInformation(String dietaryInformation) {
		this.dietaryInformation = dietaryInformation;
	}

	@Column(name = "IS_SPICY")
	public Integer getIsSpicy() {
		return this.isSpicy;
	}

	public void setIsSpicy(Integer isSpicy) {
		this.isSpicy = isSpicy;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

}
