package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ItemAddon generated by hbm2java
 */
@Entity
@Table(name = "item_addon", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEM_ID", "ADDON_ID" }))
public class ItemAddon implements java.io.Serializable {

	private Long itemAddonId;
	private Addons addons;
	private Item item;
	private BigDecimal price;
	private Integer isActive;
	private Set<OrderItemAddon> orderItemAddons = new HashSet<OrderItemAddon>(0);

	public ItemAddon() {
	}

	public ItemAddon(Addons addons, Item item, BigDecimal price) {
		this.addons = addons;
		this.item = item;
		this.price = price;
	}

	public ItemAddon(Addons addons, Item item, BigDecimal price,
			Integer isActive, Set<OrderItemAddon> orderItemAddons) {
		this.addons = addons;
		this.item = item;
		this.price = price;
		this.isActive = isActive;
		this.orderItemAddons = orderItemAddons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_ADDON_ID", unique = true, nullable = false)
	public Long getItemAddonId() {
		return this.itemAddonId;
	}

	public void setItemAddonId(Long itemAddonId) {
		this.itemAddonId = itemAddonId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDON_ID", nullable = false)
	public Addons getAddons() {
		return this.addons;
	}

	public void setAddons(Addons addons) {
		this.addons = addons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemAddon")
	public Set<OrderItemAddon> getOrderItemAddons() {
		return this.orderItemAddons;
	}

	public void setOrderItemAddons(Set<OrderItemAddon> orderItemAddons) {
		this.orderItemAddons = orderItemAddons;
	}

}
