package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemMediaContent generated by hbm2java
 */
@Entity
@Table(name = "item_media_content")
public class ItemMediaContent implements java.io.Serializable {

	private Long itemMediaId;
	private Item item;
	private VedioSourceType vedioSourceType;
	private String imageUrl;
	private String vedioUrl;
	private int displayOrder;
	private Integer isActive;

	public ItemMediaContent() {
	}

	public ItemMediaContent(Item item, String imageUrl, int displayOrder) {
		this.item = item;
		this.imageUrl = imageUrl;
		this.displayOrder = displayOrder;
	}

	public ItemMediaContent(Item item, VedioSourceType vedioSourceType,
			String imageUrl, String vedioUrl, int displayOrder, Integer isActive) {
		this.item = item;
		this.vedioSourceType = vedioSourceType;
		this.imageUrl = imageUrl;
		this.vedioUrl = vedioUrl;
		this.displayOrder = displayOrder;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_MEDIA_ID", unique = true, nullable = false)
	public Long getItemMediaId() {
		return this.itemMediaId;
	}

	public void setItemMediaId(Long itemMediaId) {
		this.itemMediaId = itemMediaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEDIO_SOURCE_ID")
	public VedioSourceType getVedioSourceType() {
		return this.vedioSourceType;
	}

	public void setVedioSourceType(VedioSourceType vedioSourceType) {
		this.vedioSourceType = vedioSourceType;
	}

	@Column(name = "IMAGE_URL", nullable = false)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "VEDIO_URL")
	public String getVedioUrl() {
		return this.vedioUrl;
	}

	public void setVedioUrl(String vedioUrl) {
		this.vedioUrl = vedioUrl;
	}

	@Column(name = "DISPLAY_ORDER", nullable = false)
	public int getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

}
