package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemIngredient generated by hbm2java
 */
@Entity
@Table(name = "item_ingredient")
public class ItemIngredient implements java.io.Serializable {

	private Long itemIngredientId;
	private Item item;
	private Ingredients ingredients;

	public ItemIngredient() {
	}

	public ItemIngredient(Item item, Ingredients ingredients) {
		this.item = item;
		this.ingredients = ingredients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_INGREDIENT_ID", unique = true, nullable = false)
	public Long getItemIngredientId() {
		return this.itemIngredientId;
	}

	public void setItemIngredientId(Long itemIngredientId) {
		this.itemIngredientId = itemIngredientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INGREDIENT_ID", nullable = false)
	public Ingredients getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Ingredients ingredients) {
		this.ingredients = ingredients;
	}

}
