package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import static com.icarte.commons.Constants.NamedQueries.FIND_CATEGORIES_BY_MENU_ID;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * ItemCategory generated by hbm2java
 */
@Entity
@Table(name = "item_category", uniqueConstraints = @UniqueConstraint(columnNames = {
		"RESTURANT_ID", "MENU_ID" }))
@NamedQueries({ @NamedQuery(name = FIND_CATEGORIES_BY_MENU_ID, query = "from ItemCategory category inner join fetch category.itemCategoryTranslations categoryTrans inner join fetch category.menu menu inner join fetch categoryTrans.refLanguages lang inner join fetch menu.resturant rest where menu.menuId = :menuId order by category.priority") })
public class ItemCategory implements java.io.Serializable {

	private Long itemCategoryId;
	private String imageUrl;
	private String smallIconUrl;
	private String largeIconUrl;
	private long parentCategory;
	private String tags;
	private Date availableDurationStart;
	private Date availableDurationEnd;
	private long resturantId;
	private Integer isActive;
	private Integer priority;
	
	private Set<ItemCategoryTranslation> itemCategoryTranslations = new HashSet<ItemCategoryTranslation>(
			0);
	private Set<Item> items = new HashSet<Item>(0);

	private Menu menu;

	public ItemCategory() {
	}

	public ItemCategory(String imageUrl, String smallIconUrl,
			String largeIconUrl, long parentCategory, long menuId,
			long resturantId) {
		this.imageUrl = imageUrl;
		this.smallIconUrl = smallIconUrl;
		this.largeIconUrl = largeIconUrl;
		this.parentCategory = parentCategory;
		this.resturantId = resturantId;
	}

	public ItemCategory(String imageUrl, String smallIconUrl,
			String largeIconUrl, long parentCategory, String tags, long menuId,
			Date availableDurationStart, Date availableDurationEnd,
			long resturantId, Integer isActive,
			Set<ItemCategoryTranslation> itemCategoryTranslations,
			Set<Item> items) {
		this.imageUrl = imageUrl;
		this.smallIconUrl = smallIconUrl;
		this.largeIconUrl = largeIconUrl;
		this.parentCategory = parentCategory;
		this.tags = tags;
		this.availableDurationStart = availableDurationStart;
		this.availableDurationEnd = availableDurationEnd;
		this.resturantId = resturantId;
		this.isActive = isActive;
		this.itemCategoryTranslations = itemCategoryTranslations;
		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_CATEGORY_ID", unique = true, nullable = false)
	public Long getItemCategoryId() {
		return this.itemCategoryId;
	}

	public void setItemCategoryId(Long itemCategoryId) {
		this.itemCategoryId = itemCategoryId;
	}

	@Column(name = "IMAGE_URL", nullable = false)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "SMALL_ICON_URL", nullable = false)
	public String getSmallIconUrl() {
		return this.smallIconUrl;
	}

	public void setSmallIconUrl(String smallIconUrl) {
		this.smallIconUrl = smallIconUrl;
	}

	@Column(name = "LARGE_ICON_URL", nullable = false)
	public String getLargeIconUrl() {
		return this.largeIconUrl;
	}

	public void setLargeIconUrl(String largeIconUrl) {
		this.largeIconUrl = largeIconUrl;
	}

	@Column(name = "PARENT_CATEGORY", nullable = false)
	public long getParentCategory() {
		return this.parentCategory;
	}

	public void setParentCategory(long parentCategory) {
		this.parentCategory = parentCategory;
	}

	@Column(name = "TAGS", length = 500)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "AVAILABLE_DURATION_START", length = 8)
	public Date getAvailableDurationStart() {
		return this.availableDurationStart;
	}

	public void setAvailableDurationStart(Date availableDurationStart) {
		this.availableDurationStart = availableDurationStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "AVAILABLE_DURATION_END", length = 8)
	public Date getAvailableDurationEnd() {
		return this.availableDurationEnd;
	}

	public void setAvailableDurationEnd(Date availableDurationEnd) {
		this.availableDurationEnd = availableDurationEnd;
	}

	@Column(name = "RESTURANT_ID", nullable = false)
	public long getResturantId() {
		return this.resturantId;
	}

	public void setResturantId(long resturantId) {
		this.resturantId = resturantId;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemCategory")
	public Set<ItemCategoryTranslation> getItemCategoryTranslations() {
		return this.itemCategoryTranslations;
	}

	public void setItemCategoryTranslations(
			Set<ItemCategoryTranslation> itemCategoryTranslations) {
		this.itemCategoryTranslations = itemCategoryTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemCategory")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_ID", nullable = false)
	public Menu getMenu() {
		return menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "PRIORITY")
	public Integer getPriority() {
		return priority;
	}
	
	public void setPriority(Integer priority) {
		this.priority = priority;
	}
	
	//
	// /**
	// * Return Object JSON for this Class
	// */
	// @Transient
	// public String toString(){
	// StringBuilder objectJSON = new StringBuilder("{")
	// .append("\"itemCategoryId\" : ").append(itemCategoryId).append(",")
	// .append("\"imageUrl\" : \"").append(imageUrl).append("\",")
	// .append("\"smallIconUrl\" : \"").append(smallIconUrl).append("\",")
	// .append("\"largeIconUrl\" : \"").append(largeIconUrl).append("\",")
	// .append("\"parentCategory\" : ").append(parentCategory).append(",")
	// .append("\"tags\" : \"").append(tags).append("\",")
	// .append("\"availableDurationStart\" : \"").append(availableDurationStart).append("\",")
	// .append("\"availableDurationEnd\" : \"").append(availableDurationEnd).append("\",")
	// .append("\"resturantId\" : ").append(resturantId).append(",")
	// .append("\"isActive\" : ").append(isActive)
	// .append("}");
	//
	//
	// return objectJSON.toString();
	//
	//
	// }
}
