package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemDiscount generated by hbm2java
 */
@Entity
@Table(name = "item_discount")
public class ItemDiscount implements java.io.Serializable {

	private Long itemDiscountId;
	private ItemVariant itemVariant;
	private BigDecimal discountPrice;
	private Date startDate;
	private Date endDate;
	private Integer isActive;

	public ItemDiscount() {
	}

	public ItemDiscount(BigDecimal discountPrice, Date startDate, Date endDate) {
		this.discountPrice = discountPrice;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public ItemDiscount(ItemVariant itemVariant, BigDecimal discountPrice,
			Date startDate, Date endDate, Integer isActive) {
		this.itemVariant = itemVariant;
		this.discountPrice = discountPrice;
		this.startDate = startDate;
		this.endDate = endDate;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_DISCOUNT_ID", unique = true, nullable = false)
	public Long getItemDiscountId() {
		return this.itemDiscountId;
	}

	public void setItemDiscountId(Long itemDiscountId) {
		this.itemDiscountId = itemDiscountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_VARIANT_ID")
	public ItemVariant getItemVariant() {
		return this.itemVariant;
	}

	public void setItemVariant(ItemVariant itemVariant) {
		this.itemVariant = itemVariant;
	}

	@Column(name = "DISCOUNT_PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(BigDecimal discountPrice) {
		this.discountPrice = discountPrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

}
