package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ItemVariant generated by hbm2java
 */
@Entity
@Table(name = "item_variant", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEM_ID", "VARIANT_ID" }))
public class ItemVariant implements java.io.Serializable {

	private Long itemVariantId;
	private Item item;
	private BigDecimal price;
	private int approxPreperationTime;
	private Integer isActive;
	private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);
	private Set<ItemDiscount> itemDiscounts = new HashSet<ItemDiscount>(0);
	private Variant variant;
	
	public ItemVariant() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_VARIANT_ID", unique = true, nullable = false)
	public Long getItemVariantId() {
		return this.itemVariantId;
	}

	public void setItemVariantId(Long itemVariantId) {
		this.itemVariantId = itemVariantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public Item getItem() {
		return item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	
//	@Column(name = "VARIANT_ID", nullable = false)
//	public long getVariantId() {
//		return this.variantId;
//	}
//
//	public void setVariantId(long variantId) {
//		this.variantId = variantId;
//	}

	@Column(name = "PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "APPROX_PREPERATION_TIME", nullable = false)
	public int getApproxPreperationTime() {
		return this.approxPreperationTime;
	}

	public void setApproxPreperationTime(int approxPreperationTime) {
		this.approxPreperationTime = approxPreperationTime;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemVariant")
	public Set<OrderItems> getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set<OrderItems> orderItemses) {
		this.orderItemses = orderItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemVariant")
	public Set<ItemDiscount> getItemDiscounts() {
		return this.itemDiscounts;
	}

	public void setItemDiscounts(Set<ItemDiscount> itemDiscounts) {
		this.itemDiscounts = itemDiscounts;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VARIANT_ID", nullable = false)
	public Variant getVariant() {
		return variant;
	}
	
	public void setVariant(Variant variant) {
		this.variant = variant;
	}
}
