package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import static com.icarte.commons.Constants.NamedQueries.FIND_MENU_BY_REST_ID;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Menu generated by hbm2java
 */

@NamedQueries({
	@NamedQuery(name =FIND_MENU_BY_REST_ID , query="from Menu menu inner join fetch menu.resturant resturant where resturant.resturantId = :resturantId and menu.isActive = 1")
})
@Entity
@Table(name = "menu")
public class Menu implements java.io.Serializable {

	private Long menuId;
	private Resturant resturant;
	private String title;
	private Integer isActive;
	private Set<ItemCategory> itemCategories = new HashSet<ItemCategory>(0);
	public Menu() {
	}

	public Menu(Resturant resturant, String title) {
		this.resturant = resturant;
		this.title = title;
	}

	public Menu(Resturant resturant, String title, Integer isActive) {
		this.resturant = resturant;
		this.title = title;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MENU_ID", unique = true, nullable = false)
	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<ItemCategory> getItemCategories() {
		return itemCategories;
	}
	
	public void setItemCategories(Set<ItemCategory> itemCategories) {
		this.itemCategories = itemCategories;
	}
	

}
