package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderSpecialDealItem generated by hbm2java
 */
@Entity
@Table(name = "order_special_deal_item")
public class OrderSpecialDealItem implements java.io.Serializable {

	private Long orderSpecialDealItemId;
	private Orders orders;
	private SpecialDealItem specialDealItem;
	private int quantity;
	private String specialRemarks;
	private BigDecimal orderPrice;

	public OrderSpecialDealItem() {
	}

	public OrderSpecialDealItem(Orders orders, SpecialDealItem specialDealItem,
			int quantity, BigDecimal orderPrice) {
		this.orders = orders;
		this.specialDealItem = specialDealItem;
		this.quantity = quantity;
		this.orderPrice = orderPrice;
	}

	public OrderSpecialDealItem(Orders orders, SpecialDealItem specialDealItem,
			int quantity, String specialRemarks, BigDecimal orderPrice) {
		this.orders = orders;
		this.specialDealItem = specialDealItem;
		this.quantity = quantity;
		this.specialRemarks = specialRemarks;
		this.orderPrice = orderPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_SPECIAL_DEAL_ITEM_ID", unique = true, nullable = false)
	public Long getOrderSpecialDealItemId() {
		return this.orderSpecialDealItemId;
	}

	public void setOrderSpecialDealItemId(Long orderSpecialDealItemId) {
		this.orderSpecialDealItemId = orderSpecialDealItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEAL_DEAL_ITEM_ID", nullable = false)
	public SpecialDealItem getSpecialDealItem() {
		return this.specialDealItem;
	}

	public void setSpecialDealItem(SpecialDealItem specialDealItem) {
		this.specialDealItem = specialDealItem;
	}

	@Column(name = "QUANTITY", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "SPECIAL_REMARKS")
	public String getSpecialRemarks() {
		return this.specialRemarks;
	}

	public void setSpecialRemarks(String specialRemarks) {
		this.specialRemarks = specialRemarks;
	}

	@Column(name = "ORDER_PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

}
