package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name = "order_items")
public class OrderItems implements java.io.Serializable {

	private Long orderItem;
	private ItemVariant itemVariant;
	private Orders orders;
	private long quantity;
	private String specialRemarks;
	private BigDecimal orderPrice;

	public OrderItems() {
	}

	public OrderItems(ItemVariant itemVariant, Orders orders, long quantity,
			BigDecimal orderPrice) {
		this.itemVariant = itemVariant;
		this.orders = orders;
		this.quantity = quantity;
		this.orderPrice = orderPrice;
	}

	public OrderItems(ItemVariant itemVariant, Orders orders, long quantity,
			String specialRemarks, BigDecimal orderPrice) {
		this.itemVariant = itemVariant;
		this.orders = orders;
		this.quantity = quantity;
		this.specialRemarks = specialRemarks;
		this.orderPrice = orderPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_ITEM", unique = true, nullable = false)
	public Long getOrderItem() {
		return this.orderItem;
	}

	public void setOrderItem(Long orderItem) {
		this.orderItem = orderItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_VARIANT_ID", nullable = false)
	public ItemVariant getItemVariant() {
		return this.itemVariant;
	}

	public void setItemVariant(ItemVariant itemVariant) {
		this.itemVariant = itemVariant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "QUANTITY", nullable = false)
	public long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(long quantity) {
		this.quantity = quantity;
	}

	@Column(name = "SPECIAL_REMARKS", length = 500)
	public String getSpecialRemarks() {
		return this.specialRemarks;
	}

	public void setSpecialRemarks(String specialRemarks) {
		this.specialRemarks = specialRemarks;
	}

	@Column(name = "ORDER_PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

}
