package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders")
public class Orders implements java.io.Serializable {

	private Long orderId;
	private Staff staff;
	private Branch branch;
	private Customer customer;
	private ServingTable servingTable;
	private String referenceNum;
	private Date orderDate;
	private String specialRemarks;
	private long orderStatus;
	private String cancellationReason;
	private BigDecimal discountAppliedPct;
	private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
	private Set<OrderItemAddon> orderItemAddons = new HashSet<OrderItemAddon>(0);
	private Set<OrderSpecialDealItem> orderSpecialDealItems = new HashSet<OrderSpecialDealItem>(
			0);

	public Orders() {
	}

	public Orders(Staff staff, Branch branch, Customer customer,
			ServingTable servingTable, String referenceNum, Date orderDate,
			long orderStatus) {
		this.staff = staff;
		this.branch = branch;
		this.customer = customer;
		this.servingTable = servingTable;
		this.referenceNum = referenceNum;
		this.orderDate = orderDate;
		this.orderStatus = orderStatus;
	}

	public Orders(Staff staff, Branch branch, Customer customer,
			ServingTable servingTable, String referenceNum, Date orderDate,
			String specialRemarks, long orderStatus, String cancellationReason,
			BigDecimal discountAppliedPct, Set<OrderItems> orderItemses,
			Set<Feedback> feedbacks, Set<OrderItemAddon> orderItemAddons,
			Set<OrderSpecialDealItem> orderSpecialDealItems) {
		this.staff = staff;
		this.branch = branch;
		this.customer = customer;
		this.servingTable = servingTable;
		this.referenceNum = referenceNum;
		this.orderDate = orderDate;
		this.specialRemarks = specialRemarks;
		this.orderStatus = orderStatus;
		this.cancellationReason = cancellationReason;
		this.discountAppliedPct = discountAppliedPct;
		this.orderItemses = orderItemses;
		this.feedbacks = feedbacks;
		this.orderItemAddons = orderItemAddons;
		this.orderSpecialDealItems = orderSpecialDealItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_ID", unique = true, nullable = false)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STAFF_ID", nullable = false)
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRANCH_ID", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVING_TABLE_ID", nullable = false)
	public ServingTable getServingTable() {
		return this.servingTable;
	}

	public void setServingTable(ServingTable servingTable) {
		this.servingTable = servingTable;
	}

	@Column(name = "REFERENCE_NUM", nullable = false)
	public String getReferenceNum() {
		return this.referenceNum;
	}

	public void setReferenceNum(String referenceNum) {
		this.referenceNum = referenceNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_DATE", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "SPECIAL_REMARKS", length = 500)
	public String getSpecialRemarks() {
		return this.specialRemarks;
	}

	public void setSpecialRemarks(String specialRemarks) {
		this.specialRemarks = specialRemarks;
	}

	@Column(name = "ORDER_STATUS", nullable = false)
	public long getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(long orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "CANCELLATION_REASON", length = 500)
	public String getCancellationReason() {
		return this.cancellationReason;
	}

	public void setCancellationReason(String cancellationReason) {
		this.cancellationReason = cancellationReason;
	}

	@Column(name = "DISCOUNT_APPLIED_PCT", precision = 5, scale = 3)
	public BigDecimal getDiscountAppliedPct() {
		return this.discountAppliedPct;
	}

	public void setDiscountAppliedPct(BigDecimal discountAppliedPct) {
		this.discountAppliedPct = discountAppliedPct;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders" , cascade = CascadeType.ALL)
	public Set<OrderItems> getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set<OrderItems> orderItemses) {
		this.orderItemses = orderItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<OrderItemAddon> getOrderItemAddons() {
		return this.orderItemAddons;
	}

	public void setOrderItemAddons(Set<OrderItemAddon> orderItemAddons) {
		this.orderItemAddons = orderItemAddons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<OrderSpecialDealItem> getOrderSpecialDealItems() {
		return this.orderSpecialDealItems;
	}

	public void setOrderSpecialDealItems(
			Set<OrderSpecialDealItem> orderSpecialDealItems) {
		this.orderSpecialDealItems = orderSpecialDealItems;
	}

}
