package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderItemAddon generated by hbm2java
 */
@Entity
@Table(name = "order_item_addon")
public class OrderItemAddon implements java.io.Serializable {

	private Long orderItemAddonId;
	private Orders orders;
	private ItemAddon itemAddon;
	private BigDecimal price;
	private String specialRemarks;
	private int quantity;

	public OrderItemAddon() {
	}

	public OrderItemAddon(Orders orders, ItemAddon itemAddon, BigDecimal price,
			int quantity) {
		this.orders = orders;
		this.itemAddon = itemAddon;
		this.price = price;
		this.quantity = quantity;
	}

	public OrderItemAddon(Orders orders, ItemAddon itemAddon, BigDecimal price,
			String specialRemarks, int quantity) {
		this.orders = orders;
		this.itemAddon = itemAddon;
		this.price = price;
		this.specialRemarks = specialRemarks;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_ITEM_ADDON_ID", unique = true, nullable = false)
	public Long getOrderItemAddonId() {
		return this.orderItemAddonId;
	}

	public void setOrderItemAddonId(Long orderItemAddonId) {
		this.orderItemAddonId = orderItemAddonId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ADDON_ID", nullable = false)
	public ItemAddon getItemAddon() {
		return this.itemAddon;
	}

	public void setItemAddon(ItemAddon itemAddon) {
		this.itemAddon = itemAddon;
	}

	@Column(name = "PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "SPECIAL_REMARKS", length = 500)
	public String getSpecialRemarks() {
		return this.specialRemarks;
	}

	public void setSpecialRemarks(String specialRemarks) {
		this.specialRemarks = specialRemarks;
	}

	@Column(name = "QUANTITY", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
