package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefLanguages generated by hbm2java
 */
@Entity
@Table(name = "ref_languages")
public class RefLanguages implements java.io.Serializable {

	private Long languageId;
	private String name;
	private String code;
	private Integer isActive;
	private Set<ItemTranslation> itemTranslations = new HashSet<ItemTranslation>(
			0);
	private Set<IngredientTranslation> ingredientTranslations = new HashSet<IngredientTranslation>(
			0);
	private Set<SpecialDealTranslation> specialDealTranslations = new HashSet<SpecialDealTranslation>(
			0);
	private Set<CuisineTranslation> cuisineTranslations = new HashSet<CuisineTranslation>(
			0);
	private Set<ResturantTranslation> resturantTranslations = new HashSet<ResturantTranslation>(
			0);
	private Set<ResturantLanguage> resturantLanguages = new HashSet<ResturantLanguage>(
			0);
	private Set<ItemCategoryTranslation> itemCategoryTranslations = new HashSet<ItemCategoryTranslation>(
			0);
	private Set<VariantTranslation> variantTranslations = new HashSet<VariantTranslation>(
			0);
	private Set<SpiceTypeTranslation> spiceTypeTranslations = new HashSet<SpiceTypeTranslation>(
			0);
	private Set<AddonTranslation> addonTranslations = new HashSet<AddonTranslation>(
			0);
	private Set<FeedbackTranslation> feedbackTranslations = new HashSet<FeedbackTranslation>(
			0);

	public RefLanguages() {
	}

	public RefLanguages(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public RefLanguages(String name, String code, Integer isActive,
			Set<ItemTranslation> itemTranslations,
			Set<IngredientTranslation> ingredientTranslations,
			Set<SpecialDealTranslation> specialDealTranslations,
			Set<CuisineTranslation> cuisineTranslations,
			Set<ResturantTranslation> resturantTranslations,
			Set<ResturantLanguage> resturantLanguages,
			Set<ItemCategoryTranslation> itemCategoryTranslations,
			Set<VariantTranslation> variantTranslations,
			Set<SpiceTypeTranslation> spiceTypeTranslations,
			Set<AddonTranslation> addonTranslations,
			Set<FeedbackTranslation> feedbackTranslations) {
		this.name = name;
		this.code = code;
		this.isActive = isActive;
		this.itemTranslations = itemTranslations;
		this.ingredientTranslations = ingredientTranslations;
		this.specialDealTranslations = specialDealTranslations;
		this.cuisineTranslations = cuisineTranslations;
		this.resturantTranslations = resturantTranslations;
		this.resturantLanguages = resturantLanguages;
		this.itemCategoryTranslations = itemCategoryTranslations;
		this.variantTranslations = variantTranslations;
		this.spiceTypeTranslations = spiceTypeTranslations;
		this.addonTranslations = addonTranslations;
		this.feedbackTranslations = feedbackTranslations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LANGUAGE_ID", unique = true, nullable = false)
	public Long getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Long languageId) {
		this.languageId = languageId;
	}

	@Column(name = "NAME", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", nullable = false, length = 4)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<ItemTranslation> getItemTranslations() {
		return this.itemTranslations;
	}

	public void setItemTranslations(Set<ItemTranslation> itemTranslations) {
		this.itemTranslations = itemTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<IngredientTranslation> getIngredientTranslations() {
		return this.ingredientTranslations;
	}

	public void setIngredientTranslations(
			Set<IngredientTranslation> ingredientTranslations) {
		this.ingredientTranslations = ingredientTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<SpecialDealTranslation> getSpecialDealTranslations() {
		return this.specialDealTranslations;
	}

	public void setSpecialDealTranslations(
			Set<SpecialDealTranslation> specialDealTranslations) {
		this.specialDealTranslations = specialDealTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<CuisineTranslation> getCuisineTranslations() {
		return this.cuisineTranslations;
	}

	public void setCuisineTranslations(
			Set<CuisineTranslation> cuisineTranslations) {
		this.cuisineTranslations = cuisineTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<ResturantTranslation> getResturantTranslations() {
		return this.resturantTranslations;
	}

	public void setResturantTranslations(
			Set<ResturantTranslation> resturantTranslations) {
		this.resturantTranslations = resturantTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<ResturantLanguage> getResturantLanguages() {
		return this.resturantLanguages;
	}

	public void setResturantLanguages(Set<ResturantLanguage> resturantLanguages) {
		this.resturantLanguages = resturantLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<ItemCategoryTranslation> getItemCategoryTranslations() {
		return this.itemCategoryTranslations;
	}

	public void setItemCategoryTranslations(
			Set<ItemCategoryTranslation> itemCategoryTranslations) {
		this.itemCategoryTranslations = itemCategoryTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<VariantTranslation> getVariantTranslations() {
		return this.variantTranslations;
	}

	public void setVariantTranslations(
			Set<VariantTranslation> variantTranslations) {
		this.variantTranslations = variantTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<SpiceTypeTranslation> getSpiceTypeTranslations() {
		return this.spiceTypeTranslations;
	}

	public void setSpiceTypeTranslations(
			Set<SpiceTypeTranslation> spiceTypeTranslations) {
		this.spiceTypeTranslations = spiceTypeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<AddonTranslation> getAddonTranslations() {
		return this.addonTranslations;
	}

	public void setAddonTranslations(Set<AddonTranslation> addonTranslations) {
		this.addonTranslations = addonTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLanguages")
	public Set<FeedbackTranslation> getFeedbackTranslations() {
		return this.feedbackTranslations;
	}

	public void setFeedbackTranslations(
			Set<FeedbackTranslation> feedbackTranslations) {
		this.feedbackTranslations = feedbackTranslations;
	}

}
