package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResturantLanguage generated by hbm2java
 */
@Entity
@Table(name = "resturant_language", uniqueConstraints = @UniqueConstraint(columnNames = {
		"RESTURANT_ID", "LANGUAGE_ID" }))
public class ResturantLanguage implements java.io.Serializable {

	private Long resturantLanguageId;
	private Resturant resturant;
	private RefLanguages refLanguages;
	private Integer isActive;

	public ResturantLanguage() {
	}

	public ResturantLanguage(Resturant resturant, RefLanguages refLanguages) {
		this.resturant = resturant;
		this.refLanguages = refLanguages;
	}

	public ResturantLanguage(Resturant resturant, RefLanguages refLanguages,
			Integer isActive) {
		this.resturant = resturant;
		this.refLanguages = refLanguages;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RESTURANT_LANGUAGE_ID", unique = true, nullable = false)
	public Long getResturantLanguageId() {
		return this.resturantLanguageId;
	}

	public void setResturantLanguageId(Long resturantLanguageId) {
		this.resturantLanguageId = resturantLanguageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

}
