package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Resturant generated by hbm2java
 */
@Entity
@Table(name = "resturant", uniqueConstraints = @UniqueConstraint(columnNames = "ACTIVATION_KEY"))
public class Resturant implements java.io.Serializable {

	private Long resturantId;
	private AccountType accountType;
	private String activationKey;
	private String contactPerson;
	private String logoSmall;
	private String logoLarge;
	private String theme;
	private String backgroundImage;
	private Set<Service> services = new HashSet<Service>(0);
	private Set<SpecialDeal> specialDeals = new HashSet<SpecialDeal>(0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<RestaurantDevice> restaurantDevices = new HashSet<RestaurantDevice>(
			0);
	private Set<Addons> addonses = new HashSet<Addons>(0);
	private Set<Branch> branches = new HashSet<Branch>(0);
	private Set<Ingredients> ingredientses = new HashSet<Ingredients>(0);
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<ResturantTranslation> resturantTranslations = new HashSet<ResturantTranslation>(
			0);
	private Set<SpiceType> spiceTypes = new HashSet<SpiceType>(0);
	private Set<CuisineType> cuisineTypes = new HashSet<CuisineType>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<ResturantLanguage> resturantLanguages = new HashSet<ResturantLanguage>(
			0);
	private Set<Variant> variants = new HashSet<Variant>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);

	public Resturant() {
	}

	public Resturant(AccountType accountType, String activationKey,
			String contactPerson, String logoSmall, String logoLarge) {
		this.accountType = accountType;
		this.activationKey = activationKey;
		this.contactPerson = contactPerson;
		this.logoSmall = logoSmall;
		this.logoLarge = logoLarge;
	}

	public Resturant(AccountType accountType, String activationKey,
			String contactPerson, String logoSmall, String logoLarge,
			String theme, String backgroundImage, Set<Service> services,
			Set<SpecialDeal> specialDeals, Set<Role> roles,
			Set<RestaurantDevice> restaurantDevices, Set<Addons> addonses,
			Set<Branch> branches, Set<Ingredients> ingredientses,
			Set<Users> userses,
			Set<ResturantTranslation> resturantTranslations,
			Set<SpiceType> spiceTypes, Set<CuisineType> cuisineTypes,
			Set<Customer> customers, Set<ResturantLanguage> resturantLanguages,
			Set<Variant> variants, Set<Menu> menus) {
		this.accountType = accountType;
		this.activationKey = activationKey;
		this.contactPerson = contactPerson;
		this.logoSmall = logoSmall;
		this.logoLarge = logoLarge;
		this.theme = theme;
		this.backgroundImage = backgroundImage;
		this.services = services;
		this.specialDeals = specialDeals;
		this.roles = roles;
		this.restaurantDevices = restaurantDevices;
		this.addonses = addonses;
		this.branches = branches;
		this.ingredientses = ingredientses;
		this.userses = userses;
		this.resturantTranslations = resturantTranslations;
		this.spiceTypes = spiceTypes;
		this.cuisineTypes = cuisineTypes;
		this.customers = customers;
		this.resturantLanguages = resturantLanguages;
		this.variants = variants;
		this.menus = menus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RESTURANT_ID", unique = true, nullable = false)
	public Long getResturantId() {
		return this.resturantId;
	}

	public void setResturantId(Long resturantId) {
		this.resturantId = resturantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_TYPE_ID", nullable = false)
	public AccountType getAccountType() {
		return this.accountType;
	}

	public void setAccountType(AccountType accountType) {
		this.accountType = accountType;
	}

	@Column(name = "ACTIVATION_KEY", unique = true, nullable = false, length = 25)
	public String getActivationKey() {
		return this.activationKey;
	}

	public void setActivationKey(String activationKey) {
		this.activationKey = activationKey;
	}

	@Column(name = "CONTACT_PERSON", nullable = false)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "LOGO_SMALL", nullable = false)
	public String getLogoSmall() {
		return this.logoSmall;
	}

	public void setLogoSmall(String logoSmall) {
		this.logoSmall = logoSmall;
	}

	@Column(name = "LOGO_LARGE", nullable = false)
	public String getLogoLarge() {
		return this.logoLarge;
	}

	public void setLogoLarge(String logoLarge) {
		this.logoLarge = logoLarge;
	}

	@Column(name = "THEME", length = 5)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "BACKGROUND_IMAGE")
	public String getBackgroundImage() {
		return this.backgroundImage;
	}

	public void setBackgroundImage(String backgroundImage) {
		this.backgroundImage = backgroundImage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<SpecialDeal> getSpecialDeals() {
		return this.specialDeals;
	}

	public void setSpecialDeals(Set<SpecialDeal> specialDeals) {
		this.specialDeals = specialDeals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<RestaurantDevice> getRestaurantDevices() {
		return this.restaurantDevices;
	}

	public void setRestaurantDevices(Set<RestaurantDevice> restaurantDevices) {
		this.restaurantDevices = restaurantDevices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Addons> getAddonses() {
		return this.addonses;
	}

	public void setAddonses(Set<Addons> addonses) {
		this.addonses = addonses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Branch> getBranches() {
		return this.branches;
	}

	public void setBranches(Set<Branch> branches) {
		this.branches = branches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Ingredients> getIngredientses() {
		return this.ingredientses;
	}

	public void setIngredientses(Set<Ingredients> ingredientses) {
		this.ingredientses = ingredientses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<ResturantTranslation> getResturantTranslations() {
		return this.resturantTranslations;
	}

	public void setResturantTranslations(
			Set<ResturantTranslation> resturantTranslations) {
		this.resturantTranslations = resturantTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<SpiceType> getSpiceTypes() {
		return this.spiceTypes;
	}

	public void setSpiceTypes(Set<SpiceType> spiceTypes) {
		this.spiceTypes = spiceTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<CuisineType> getCuisineTypes() {
		return this.cuisineTypes;
	}

	public void setCuisineTypes(Set<CuisineType> cuisineTypes) {
		this.cuisineTypes = cuisineTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<ResturantLanguage> getResturantLanguages() {
		return this.resturantLanguages;
	}

	public void setResturantLanguages(Set<ResturantLanguage> resturantLanguages) {
		this.resturantLanguages = resturantLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Variant> getVariants() {
		return this.variants;
	}

	public void setVariants(Set<Variant> variants) {
		this.variants = variants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resturant")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

}
