package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResturantTranslation generated by hbm2java
 */
@Entity
@Table(name = "resturant_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"RESTURANT_ID", "LANGUAGE_ID" }))
public class ResturantTranslation implements java.io.Serializable {

	private Long resturantTransId;
	private Resturant resturant;
	private RefLanguages refLanguages;
	private String title;
	private String description;
	private Integer showDescription;

	public ResturantTranslation() {
	}

	public ResturantTranslation(Resturant resturant, RefLanguages refLanguages,
			String title, String description) {
		this.resturant = resturant;
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
	}

	public ResturantTranslation(Resturant resturant, RefLanguages refLanguages,
			String title, String description, Integer showDescription) {
		this.resturant = resturant;
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RESTURANT_TRANS_ID", unique = true, nullable = false)
	public Long getResturantTransId() {
		return this.resturantTransId;
	}

	public void setResturantTransId(Long resturantTransId) {
		this.resturantTransId = resturantTransId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

}
