package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RestaurantDevice generated by hbm2java
 */
@Entity
@Table(name = "restaurant_device")
public class RestaurantDevice implements java.io.Serializable {

	private Long restaurantDeviceId;
	private Resturant resturant;
	private long deviceId;
	private String deviceManufecturer;
	private Date lastLoginTime;
	private Integer isActive;
	private Date activatedOn;
	private Integer isBlocked;
	private Date blockedOn;
	private String activatedBy;
	private String blockedBy;
	private String registrationCode;
	
	
	public RestaurantDevice() {
	}

	public RestaurantDevice(Resturant resturant, long deviceId,
			String deviceManufecturer) {
		this.resturant = resturant;
		this.deviceId = deviceId;
		this.deviceManufecturer = deviceManufecturer;
	}

	public RestaurantDevice(Resturant resturant, long deviceId,
			String deviceManufecturer, Date lastLoginTime, Integer isActive,
			Date activatedOn, Integer isBlocked, Date blockedOn,
			String activatedBy, String blockedBy) {
		this.resturant = resturant;
		this.deviceId = deviceId;
		this.deviceManufecturer = deviceManufecturer;
		this.lastLoginTime = lastLoginTime;
		this.isActive = isActive;
		this.activatedOn = activatedOn;
		this.isBlocked = isBlocked;
		this.blockedOn = blockedOn;
		this.activatedBy = activatedBy;
		this.blockedBy = blockedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RESTAURANT_DEVICE_ID", unique = true, nullable = false)
	public Long getRestaurantDeviceId() {
		return this.restaurantDeviceId;
	}

	public void setRestaurantDeviceId(Long restaurantDeviceId) {
		this.restaurantDeviceId = restaurantDeviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "DEVICE_ID", nullable = false)
	public long getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(long deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "DEVICE_MANUFECTURER", nullable = false)
	public String getDeviceManufecturer() {
		return this.deviceManufecturer;
	}

	public void setDeviceManufecturer(String deviceManufecturer) {
		this.deviceManufecturer = deviceManufecturer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_LOGIN_TIME", length = 10)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACTIVATED_ON", length = 10)
	public Date getActivatedOn() {
		return this.activatedOn;
	}

	public void setActivatedOn(Date activatedOn) {
		this.activatedOn = activatedOn;
	}

	@Column(name = "IS_BLOCKED")
	public Integer getIsBlocked() {
		return this.isBlocked;
	}

	public void setIsBlocked(Integer isBlocked) {
		this.isBlocked = isBlocked;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BLOCKED_ON", length = 10)
	public Date getBlockedOn() {
		return this.blockedOn;
	}

	public void setBlockedOn(Date blockedOn) {
		this.blockedOn = blockedOn;
	}

	@Column(name = "ACTIVATED_BY")
	public String getActivatedBy() {
		return this.activatedBy;
	}

	public void setActivatedBy(String activatedBy) {
		this.activatedBy = activatedBy;
	}

	@Column(name = "BLOCKED_BY")
	public String getBlockedBy() {
		return this.blockedBy;
	}

	public void setBlockedBy(String blockedBy) {
		this.blockedBy = blockedBy;
	}

	@Column(name = "REGISTRATION_CODE")
	public String getRegistrationCode() {
		return registrationCode;
	}
	
	public void setRegistrationCode(String registrationCode) {
		this.registrationCode = registrationCode;
	}
}
