package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RoleService generated by hbm2java
 */
@Entity
@Table(name = "role_service", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ROLE_ID", "SERVICE_ID" }))
public class RoleService implements java.io.Serializable {

	private Long roleServiceId;
	private Role role;
	private Service service;
	private Integer isActive;

	public RoleService() {
	}

	public RoleService(Role role, Service service) {
		this.role = role;
		this.service = service;
	}

	public RoleService(Role role, Service service, Integer isActive) {
		this.role = role;
		this.service = service;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ROLE_SERVICE_ID", unique = true, nullable = false)
	public Long getRoleServiceId() {
		return this.roleServiceId;
	}

	public void setRoleServiceId(Long roleServiceId) {
		this.roleServiceId = roleServiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICE_ID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

}
