package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "sequence_holder", uniqueConstraints = {
		@UniqueConstraint(columnNames = "ID"),
		@UniqueConstraint(columnNames = "ENTITY_TYPE") })
public class SequenceHolder implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Long id;
	private Long entityType;
	private String seqName;
	private Long nextVal;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name="ENTITY_TYPE" , unique=true , nullable=false)
	public Long getEntityType() {
		return entityType;
	}
	public void setEntityType(Long entityType) {
		this.entityType = entityType;
	}

	@Column(name="SEQ_NAME" , nullable=false)
	public String getSeqName() {
		return seqName;
	}
	public void setSeqName(String seqName) {
		this.seqName = seqName;
	}
	
	@Column(name="NEXT_VAL" , nullable=false)
	public Long getNextVal() {
		return nextVal;
	}
	public void setNextVal(Long nextVal) {
		this.nextVal = nextVal;
	}
	
	
	
	


}
