package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service")
public class Service implements java.io.Serializable {

	private Long serviceId;
	private Resturant resturant;
	private String description;
	private String name;
	private String url;
	private Integer isActive;
	private Set<RoleService> roleServices = new HashSet<RoleService>(0);

	public Service() {
	}

	public Service(Resturant resturant, String description, String name) {
		this.resturant = resturant;
		this.description = description;
		this.name = name;
	}

	public Service(Resturant resturant, String description, String name,
			String url, Integer isActive, Set<RoleService> roleServices) {
		this.resturant = resturant;
		this.description = description;
		this.name = name;
		this.url = url;
		this.isActive = isActive;
		this.roleServices = roleServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SERVICE_ID", unique = true, nullable = false)
	public Long getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Long serviceId) {
		this.serviceId = serviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<RoleService> getRoleServices() {
		return this.roleServices;
	}

	public void setRoleServices(Set<RoleService> roleServices) {
		this.roleServices = roleServices;
	}

}
