package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServingTable generated by hbm2java
 */
@Entity
@Table(name = "serving_table")
public class ServingTable implements java.io.Serializable {

	private Long servingTableId;
	private Branch branch;
	private String description;
	private String tableRefNumber;
	private Integer isActive;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public ServingTable() {
	}

	public ServingTable(Branch branch, String tableRefNumber) {
		this.branch = branch;
		this.tableRefNumber = tableRefNumber;
	}

	public ServingTable(Branch branch, String description,
			String tableRefNumber, Integer isActive, Set<Orders> orderses) {
		this.branch = branch;
		this.description = description;
		this.tableRefNumber = tableRefNumber;
		this.isActive = isActive;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SERVING_TABLE_ID", unique = true, nullable = false)
	public Long getServingTableId() {
		return this.servingTableId;
	}

	public void setServingTableId(Long servingTableId) {
		this.servingTableId = servingTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRANCH_ID", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TABLE_REF_NUMBER", nullable = false, length = 10)
	public String getTableRefNumber() {
		return this.tableRefNumber;
	}

	public void setTableRefNumber(String tableRefNumber) {
		this.tableRefNumber = tableRefNumber;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servingTable")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
