package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;
import static com.icarte.commons.Constants.NamedQueries.*;
/**
 * SpecialDealTranslation generated by hbm2java
 */

@NamedQueries({
	@NamedQuery(name =FIND_SPECIAL_DEAL_TRANS_BY_LANG  , query = "select specialDealTrans from SpecialDealTranslation specialDealTrans inner join fetch specialDealTrans.specialDeal specialDeal inner join fetch specialDealTrans.refLanguages langs inner join fetch specialDeal.resturant rest where langs.languageId = :langId and specialDeal.specialDealId = :specialDealId")
	
})
@Entity
@Table(name = "special_deal_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SPECIAL_DEAL_ID", "LANGUAGE_ID" }))
public class SpecialDealTranslation implements java.io.Serializable {

	private Long specialDealTranslationId;
	private SpecialDeal specialDeal;
	private RefLanguages refLanguages;
	private String title;
	private String description;
	private Integer showDescription;
	private String otherRemarks;

	public SpecialDealTranslation() {
	}

	public SpecialDealTranslation(SpecialDeal specialDeal,
			RefLanguages refLanguages, String title, String description) {
		this.specialDeal = specialDeal;
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
	}

	public SpecialDealTranslation(SpecialDeal specialDeal,
			RefLanguages refLanguages, String title, String description,
			Integer showDescription, String otherRemarks) {
		this.specialDeal = specialDeal;
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
		this.showDescription = showDescription;
		this.otherRemarks = otherRemarks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SPECIAL_DEAL_TRANSLATION_ID", unique = true, nullable = false)
	public Long getSpecialDealTranslationId() {
		return this.specialDealTranslationId;
	}

	public void setSpecialDealTranslationId(Long specialDealTranslationId) {
		this.specialDealTranslationId = specialDealTranslationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPECIAL_DEAL_ID", nullable = false)
	public SpecialDeal getSpecialDeal() {
		return this.specialDeal;
	}

	public void setSpecialDeal(SpecialDeal specialDeal) {
		this.specialDeal = specialDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

	@Column(name = "OTHER_REMARKS")
	public String getOtherRemarks() {
		return this.otherRemarks;
	}

	public void setOtherRemarks(String otherRemarks) {
		this.otherRemarks = otherRemarks;
	}

}
