package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpecialDealItem generated by hbm2java
 */
@Entity
@Table(name = "special_deal_item")
public class SpecialDealItem implements java.io.Serializable {

	private Long mealDealItemId;
	private SpecialDeal specialDeal;
	private Item item;
	private int quantity;
	private Set<OrderSpecialDealItem> orderSpecialDealItems = new HashSet<OrderSpecialDealItem>(
			0);

	public SpecialDealItem() {
	}

	public SpecialDealItem(SpecialDeal specialDeal, Item item, int quantity) {
		this.specialDeal = specialDeal;
		this.item = item;
		this.quantity = quantity;
	}

	public SpecialDealItem(SpecialDeal specialDeal, Item item, int quantity,
			Set<OrderSpecialDealItem> orderSpecialDealItems) {
		this.specialDeal = specialDeal;
		this.item = item;
		this.quantity = quantity;
		this.orderSpecialDealItems = orderSpecialDealItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MEAL_DEAL_ITEM_ID", unique = true, nullable = false)
	public Long getMealDealItemId() {
		return this.mealDealItemId;
	}

	public void setMealDealItemId(Long mealDealItemId) {
		this.mealDealItemId = mealDealItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPECIAL_DEAL_ID", nullable = false)
	public SpecialDeal getSpecialDeal() {
		return this.specialDeal;
	}

	public void setSpecialDeal(SpecialDeal specialDeal) {
		this.specialDeal = specialDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "QUANTITY", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specialDealItem")
	public Set<OrderSpecialDealItem> getOrderSpecialDealItems() {
		return this.orderSpecialDealItems;
	}

	public void setOrderSpecialDealItems(
			Set<OrderSpecialDealItem> orderSpecialDealItems) {
		this.orderSpecialDealItems = orderSpecialDealItems;
	}

}
