package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static com.icarte.commons.Constants.NamedQueries.FIND_SPECIAL_DEAL_BY_REST_ID;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * SpecialDeal generated by hbm2java
 */
@Entity
@Table(name = "special_deal")
@NamedQueries({ @NamedQuery(name = FIND_SPECIAL_DEAL_BY_REST_ID, query = "from SpecialDeal specialDeal inner join fetch specialDeal.specialDealItems dealItems inner join fetch dealItems.item item inner join fetch specialDeal.specialDealTranslations specialDealTrans inner join fetch specialDeal.resturant resturant inner join fetch specialDealTrans.refLanguages lang where resturant.resturantId = :restaurantId") })
public class SpecialDeal implements java.io.Serializable {

	private Long specialDealId;
	private Resturant resturant;
	private Date startDate;
	private Date endDate;
	private BigDecimal price;
	private String imageUrl;
	private Integer isActive;
	private Set<SpecialDealTranslation> specialDealTranslations = new HashSet<SpecialDealTranslation>(
			0);
	private Set<SpecialDealItem> specialDealItems = new HashSet<SpecialDealItem>(
			0);

	public SpecialDeal() {
	}

	public SpecialDeal(Resturant resturant, Date startDate, Date endDate,
			BigDecimal price) {
		this.resturant = resturant;
		this.startDate = startDate;
		this.endDate = endDate;
		this.price = price;
	}

	public SpecialDeal(Resturant resturant, Date startDate, Date endDate,
			BigDecimal price, String imageUrl, Integer isActive,
			Set<SpecialDealTranslation> specialDealTranslations,
			Set<SpecialDealItem> specialDealItems) {
		this.resturant = resturant;
		this.startDate = startDate;
		this.endDate = endDate;
		this.price = price;
		this.imageUrl = imageUrl;
		this.isActive = isActive;
		this.specialDealTranslations = specialDealTranslations;
		this.specialDealItems = specialDealItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SPECIAL_DEAL_ID", unique = true, nullable = false)
	public Long getSpecialDealId() {
		return this.specialDealId;
	}

	public void setSpecialDealId(Long specialDealId) {
		this.specialDealId = specialDealId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "PRICE", nullable = false, precision = 5, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "IMAGE_URL")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specialDeal")
	public Set<SpecialDealTranslation> getSpecialDealTranslations() {
		return this.specialDealTranslations;
	}

	public void setSpecialDealTranslations(
			Set<SpecialDealTranslation> specialDealTranslations) {
		this.specialDealTranslations = specialDealTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specialDeal")
	public Set<SpecialDealItem> getSpecialDealItems() {
		return this.specialDealItems;
	}

	public void setSpecialDealItems(Set<SpecialDealItem> specialDealItems) {
		this.specialDealItems = specialDealItems;
	}

}
