package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpiceType generated by hbm2java
 */
@Entity
@Table(name = "spice_type")
public class SpiceType implements java.io.Serializable {

	private Long spiceTypeId;
	private Resturant resturant;
	private String imageUrl;
	private Integer isActive;
	private Set<SpiceTypeTranslation> spiceTypeTranslations = new HashSet<SpiceTypeTranslation>(
			0);
	private Set<Item> items = new HashSet<Item>(0);

	public SpiceType() {
	}

	public SpiceType(Resturant resturant) {
		this.resturant = resturant;
	}

	public SpiceType(Resturant resturant, String imageUrl, Integer isActive,
			Set<SpiceTypeTranslation> spiceTypeTranslations, Set<Item> items) {
		this.resturant = resturant;
		this.imageUrl = imageUrl;
		this.isActive = isActive;
		this.spiceTypeTranslations = spiceTypeTranslations;
		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SPICE_TYPE_ID", unique = true, nullable = false)
	public Long getSpiceTypeId() {
		return this.spiceTypeId;
	}

	public void setSpiceTypeId(Long spiceTypeId) {
		this.spiceTypeId = spiceTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "IMAGE_URL")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spiceType")
	public Set<SpiceTypeTranslation> getSpiceTypeTranslations() {
		return this.spiceTypeTranslations;
	}

	public void setSpiceTypeTranslations(
			Set<SpiceTypeTranslation> spiceTypeTranslations) {
		this.spiceTypeTranslations = spiceTypeTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spiceType")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
