package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SpiceTypeTranslation generated by hbm2java
 */
@Entity
@Table(name = "spice_type_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"LANGUAGE_ID", "SPICE_TYPE_ID" }))
public class SpiceTypeTranslation implements java.io.Serializable {

	private Long spiceTypeTransId;
	private SpiceType spiceType;
	private RefLanguages refLanguages;
	private String description;
	private String title;
	private Integer showDescription;

	public SpiceTypeTranslation() {
	}

	public SpiceTypeTranslation(SpiceType spiceType, RefLanguages refLanguages,
			String title) {
		this.spiceType = spiceType;
		this.refLanguages = refLanguages;
		this.title = title;
	}

	public SpiceTypeTranslation(SpiceType spiceType, RefLanguages refLanguages,
			String description, String title, Integer showDescription) {
		this.spiceType = spiceType;
		this.refLanguages = refLanguages;
		this.description = description;
		this.title = title;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SPICE_TYPE_TRANS_ID", unique = true, nullable = false)
	public Long getSpiceTypeTransId() {
		return this.spiceTypeTransId;
	}

	public void setSpiceTypeTransId(Long spiceTypeTransId) {
		this.spiceTypeTransId = spiceTypeTransId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPICE_TYPE_ID", nullable = false)
	public SpiceType getSpiceType() {
		return this.spiceType;
	}

	public void setSpiceType(SpiceType spiceType) {
		this.spiceType = spiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

}
