package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", uniqueConstraints = {
		@UniqueConstraint(columnNames = "STAFF_CODE"),
		@UniqueConstraint(columnNames = "USER_ID") })
public class Staff implements java.io.Serializable {

	private Long staffId;
	private Users users;
	private Branch branch;
	private Address address;
	private String staffCode;
	private String firstName;
	private String middleName;
	private String lastName;
	private Long mobileId;
	private Integer isActive;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Staff() {
	}

	public Staff(Users users, Branch branch, Address address, String staffCode,
			String firstName, String lastName) {
		this.users = users;
		this.branch = branch;
		this.address = address;
		this.staffCode = staffCode;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Staff(Users users, Branch branch, Address address, String staffCode,
			String firstName, String middleName, String lastName,
			Long mobileId, Integer isActive, Set<Orders> orderses) {
		this.users = users;
		this.branch = branch;
		this.address = address;
		this.staffCode = staffCode;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.mobileId = mobileId;
		this.isActive = isActive;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STAFF_ID", unique = true, nullable = false)
	public Long getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Long staffId) {
		this.staffId = staffId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", unique = true, nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRANCH_ID", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_ID", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "STAFF_CODE", unique = true, nullable = false, length = 10)
	public String getStaffCode() {
		return this.staffCode;
	}

	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	@Column(name = "FIRST_NAME", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_NAME")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LAST_NAME", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MOBILE_ID")
	public Long getMobileId() {
		return this.mobileId;
	}

	public void setMobileId(Long mobileId) {
		this.mobileId = mobileId;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
