package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

import static com.icarte.commons.Constants.NamedQueries.*;

/**
 * Users generated by hbm2java
 */


@NamedQueries({
	@NamedQuery(name = FIND_USER_BY_LOGIN,query = "from Users users where users.username = :username")
})
@Entity
@Table(name = "users", uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class Users implements java.io.Serializable {

	private Long userId;
	private Resturant resturant;
	private String username;
	private String password;
	private Integer isLocked;
	private Integer isActive;
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public Users() {
	}

	public Users(Resturant resturant, String username, String password) {
		this.resturant = resturant;
		this.username = username;
		this.password = password;
	}

	public Users(Resturant resturant, String username, String password,
			Integer isLocked, Integer isActive, Set<UserRole> userRoles,
			Set<Staff> staffs) {
		this.resturant = resturant;
		this.username = username;
		this.password = password;
		this.isLocked = isLocked;
		this.isActive = isActive;
		this.userRoles = userRoles;
		this.staffs = staffs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ID", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "USERNAME", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "IS_LOCKED")
	public Integer getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Integer isLocked) {
		this.isLocked = isLocked;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

}
