package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VariantTranslation generated by hbm2java
 */
@Entity
@Table(name = "variant_translation", uniqueConstraints = @UniqueConstraint(columnNames = {
		"VARIANT_ID", "LANGUAGE_ID" }))
public class VariantTranslation implements java.io.Serializable {

	private Long variantTransId;
	private Variant variant;
	private RefLanguages refLanguages;
	private String title;
	private String description;
	private Integer showDescription;

	public VariantTranslation() {
	}

	public VariantTranslation(Variant variant, RefLanguages refLanguages,
			String title, String description) {
		this.variant = variant;
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
	}

	public VariantTranslation(Variant variant, RefLanguages refLanguages,
			String title, String description, Integer showDescription) {
		this.variant = variant;
		this.refLanguages = refLanguages;
		this.title = title;
		this.description = description;
		this.showDescription = showDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VARIANT_TRANS_ID", unique = true, nullable = false)
	public Long getVariantTransId() {
		return this.variantTransId;
	}

	public void setVariantTransId(Long variantTransId) {
		this.variantTransId = variantTransId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VARIANT_ID", nullable = false)
	public Variant getVariant() {
		return this.variant;
	}

	public void setVariant(Variant variant) {
		this.variant = variant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", nullable = false)
	public RefLanguages getRefLanguages() {
		return this.refLanguages;
	}

	public void setRefLanguages(RefLanguages refLanguages) {
		this.refLanguages = refLanguages;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_DESCRIPTION")
	public Integer getShowDescription() {
		return this.showDescription;
	}

	public void setShowDescription(Integer showDescription) {
		this.showDescription = showDescription;
	}

}
