package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Variant generated by hbm2java
 */
@Entity
@Table(name = "variant")
public class Variant implements java.io.Serializable {

	private Long variantId;
	private Resturant resturant;
	private String imageUrl;
	private Integer isActive;
	private Set<VariantTranslation> variantTranslations = new HashSet<VariantTranslation>(0);

	public Variant() {
	}

	public Variant(Resturant resturant, String imageUrl) {
		this.resturant = resturant;
		this.imageUrl = imageUrl;
	}

	public Variant(Resturant resturant, String imageUrl, Integer isActive,
			Set<VariantTranslation> variantTranslations) {
		this.resturant = resturant;
		this.imageUrl = imageUrl;
		this.isActive = isActive;
		this.variantTranslations = variantTranslations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VARIANT_ID", unique = true, nullable = false)
	public Long getVariantId() {
		return this.variantId;
	}

	public void setVariantId(Long variantId) {
		this.variantId = variantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESTURANT_ID", nullable = false)
	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	@Column(name = "IMAGE_URL", nullable = false)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "variant")
	public Set<VariantTranslation> getVariantTranslations() {
		return this.variantTranslations;
	}

	public void setVariantTranslations(
			Set<VariantTranslation> variantTranslations) {
		this.variantTranslations = variantTranslations;
	}

}
