package com.icarte.domain;

// Generated Mar 6, 2017 11:42:17 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VedioSourceType generated by hbm2java
 */
@Entity
@Table(name = "vedio_source_type")
public class VedioSourceType implements java.io.Serializable {

	private Long vedioSourceId;
	private String name;
	private String description;
	private Integer isActive;
	private Set<ItemMediaContent> itemMediaContents = new HashSet<ItemMediaContent>(
			0);

	public VedioSourceType() {
	}

	public VedioSourceType(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public VedioSourceType(String name, String description, Integer isActive,
			Set<ItemMediaContent> itemMediaContents) {
		this.name = name;
		this.description = description;
		this.isActive = isActive;
		this.itemMediaContents = itemMediaContents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VEDIO_SOURCE_ID", unique = true, nullable = false)
	public Long getVedioSourceId() {
		return this.vedioSourceId;
	}

	public void setVedioSourceId(Long vedioSourceId) {
		this.vedioSourceId = vedioSourceId;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vedioSourceType")
	public Set<ItemMediaContent> getItemMediaContents() {
		return this.itemMediaContents;
	}

	public void setItemMediaContents(Set<ItemMediaContent> itemMediaContents) {
		this.itemMediaContents = itemMediaContents;
	}

}
