#-------------------------#
# System level properties
#-------------------------#
lengthOfOrderRefNumber=10

# apache group name
apacheGroupName = www-data

#Uploading related configurations
# LOCAL PATH
#imageRemoteURL=http://localhost/restaurant-images
#globalImagePath=D:\\wamp\\www\\restaurant-images

#PRODUCTION PATH
imageRemoteURL=http://localhost/restaurant-images
globalImagePath=/var/www/html/restaurant-images

categoriesImageFolder=category
restaurantImageFolder=restaurants
cuisineTypeImageFolder=cuisines
restaurantBgImageFolder=backgrounds
restaurantLogosFolder=logos
itemsImageFolder=items
restaurantEventImageFolder=events

#General configurations
shortDateFormat=yyyy-MM-dd
mediumDateFormat=yyyy-MM-dd HH:mm
longDateFormat=yyyy-MM-dd HH:mm:ss
approxPreparationTime=15
defaultVariantType=1
defaultVideoSourcetype=1
english=1
arabic=2
defaultCurrencySymbol=AED

# Chart related configurations
label.sales.branch=Branch Sales
label.sales.restaurant=Restaurant Sales Chart for current year
color.chart.bar.default=#00695C

#Refresh interval for loading serving table request in milli-seconds, default is 1 minute
tableRequestStatusRefreshInterval=60000

#password pattern
passwordPattern=((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#_&]).{5,20})