-- version 1.0 --
/* Add change log below 


*/
CREATE TABLE OBJECT_JSON(
	JSON_ID BIGINT NOT NULL AUTO_INCREMENT,
	record_type BIGINT NOT NULL,
	parent_id BIGINT NOT NULL,
	JSON_DATA LONGTEXT NOT NULL,
	RESTURANT_ID BIGINT NOT NULL,
	LANGUAGE_ID BIGINT NOT NULL,
	JSON_VERSION BIGINT NOT NULL,
	PRIMARY KEY(JSON_ID)
);
CREATE TABLE RESTAURANT_DEVICE(
	RESTAURANT_DEVICE_ID BIGINT NOT NULL AUTO_INCREMENT,
	DEVICE_ID BIGINT NOT NULL,
	DEVICE_MANUFECTURER VARCHAR(255) NOT NULL,
	LAST_LOGIN_TIME DATE,
	IS_ACTIVE INT(1),
	ACTIVATED_ON DATE,
	IS_BLOCKED INT(1),
	BLOCKED_ON DATE,
	ACTIVATED_BY VARCHAR(255),
	BLOCKED_BY VARCHAR(255),
	REGISTRATION_CODE VARCHAR(16),
	RESTURANT_ID BIGINT NOT NULL,
	PRIMARY KEY(RESTAURANT_DEVICE_ID)
);

CREATE TABLE ACCOUNT_TYPE(
	ACCOUNT_TYPE_ID BIGINT NOT NULL AUTO_INCREMENT,
	ACCOUNT_NAME VARCHAR(255),
	DESCRIPTION VARCHAR(500),
	PRIMARY KEY(ACCOUNT_TYPE_ID)
);

CREATE TABLE ITEM_CATEGORY_TRANSLATION (
  ITEM_CATEGORY_TRANS_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(255) DEFAULT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  LANGUAGE_ID BIGINT(20) NOT NULL,
  MENU_CATEGORY_ID BIGINT(20) NOT NULL,
  SHOW_DESCRIPTION INT(11) DEFAULT NULL,
  PRIMARY KEY (ITEM_CATEGORY_TRANS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE INGREDIENT_TRANSLATION (
  INGREDIENT_TRANS_ID BIGINT NOT NULL AUTO_INCREMENT,
  INGREDIENT_ID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(255) NULL,
  LANGUAGE_ID BIGINT NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  SHOW_DESCRIPTION INT NULL,
  PRIMARY KEY (INGREDIENT_TRANS_ID));

  --  SPICE_TYPE
  CREATE TABLE SPICE_TYPE_TRANSLATION (
  SPICE_TYPE_TRANS_ID BIGINT NOT NULL AUTO_INCREMENT,
  SPICE_TYPE_ID BIGINT NOT NULL,
  LANGUAGE_ID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(255) NULL,
  TITLE VARCHAR(255) NOT NULL,
  SHOW_DESCRIPTION INT NULL,
  PRIMARY KEY (SPICE_TYPE_TRANS_ID));
	
  --  SPICE TYPE
  CREATE TABLE SPICE_TYPE(
	SPICE_TYPE_ID BIGINT NOT NULL AUTO_INCREMENT,
	IMAGE_URL VARCHAR(255),
	IS_ACTIVE INT,
	RESTURANT_ID BIGINT NOT NULL,
	PRIMARY KEY (SPICE_TYPE_ID)
  );
  
  -- LANGUAGE
  CREATE TABLE REF_LANGUAGES(
	LANGUAGE_ID BIGINT NOT NULL  AUTO_INCREMENT,
	NAME VARCHAR(25) NOT NULL ,
	CODE  VARCHAR(4) NOT NULL,
	IS_ACTIVE INT(1),
	PRIMARY KEY (LANGUAGE_ID)
  );
  
  --  RESTURANT_LANGUAGE
  CREATE TABLE RESTURANT_LANGUAGE(
	RESTURANT_LANGUAGE_ID BIGINT NOT NULL AUTO_INCREMENT,
	LANGUAGE_ID BIGINT NOT NULL,
	RESTURANT_ID BIGINT NOT NULL,
	IS_ACTIVE INT,
	PRIMARY KEY(RESTURANT_LANGUAGE_ID)
  );
  
  --  SPECIAL DEAL TRANSLATION
  
  CREATE TABLE SPECIAL_DEAL_TRANSLATION(
	SPECIAL_DEAL_TRANSLATION_ID BIGINT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	LANGUAGE_ID BIGINT NOT NULL,
	SPECIAL_DEAL_ID BIGINT NOT NULL,
	SHOW_DESCRIPTION INT(1),
	OTHER_REMARKS VARCHAR(255),
	PRIMARY KEY (SPECIAL_DEAL_TRANSLATION_ID)
  );
  
  -- RESTURANT TRANSLATION
  CREATE TABLE RESTURANT_TRANSLATION(
	RESTURANT_TRANS_ID BIGINT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	RESTURANT_ID BIGINT NOT NULL,
	LANGUAGE_ID BIGINT NOT NULL,
	SHOW_DESCRIPTION INT(1),
	PRIMARY KEY(RESTURANT_TRANS_ID)
  );
  
  --  VARIANT TRANSLATION
  CREATE TABLE VARIANT_TRANSLATION(
	VARIANT_TRANS_ID BIGINT NOT NULL AUTO_INCREMENT,
	LANGUAGE_ID BIGINT NOT NULL,
	VARIANT_ID BIGINT NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	SHOW_DESCRIPTION INT(1),
	PRIMARY KEY(VARIANT_TRANS_ID)
	);
	
	--  VARIANT
	CREATE TABLE VARIANT(
		VARIANT_ID BIGINT NOT NULL AUTO_INCREMENT,
		IMAGE_URL VARCHAR(255) NOT NULL,
		RESTURANT_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY (VARIANT_ID)
	);
	
	--  COUSINE TRANSLATION
	CREATE TABLE CUISINE_TRANSLATION (
		CUISINE_TRANS_ID BIGINT NOT NULL AUTO_INCREMENT,
		TITLE VARCHAR(255) NOT NULL,
		DESCRIPTION VARCHAR(255) NOT NULL,
		CUISINE_TYPE_ID BIGINT NOT NULL,
		LANGUAGE_ID BIGINT NOT NULL,
		SHOW_DESCRIPTION INT(1),
		PRIMARY KEY(CUISINE_TRANS_ID)
	);
	
	-- FEEDBACK TRANSLATION
	CREATE TABLE FEEDBACK_TRANSLATION(
		FEEDBACK_TRANS_ID BIGINT NOT NULL AUTO_INCREMENT,
		TITLE VARCHAR(255) NOT NULL,
		DESCRIPTION VARCHAR(255),
		LANGUAGE_ID BIGINT NOT NULL,
		FEEDBACK_TYPE_ID BIGINT NOT NULL,
		SHOW_DESCRIPTION INT(1),
		PRIMARY KEY(FEEDBACK_TRANS_ID)
	);
	
	--  ITEM CATEGORY
	CREATE TABLE ITEM_CATEGORY(
		ITEM_CATEGORY_ID  BIGINT  NOT NULL AUTO_INCREMENT,
		IMAGE_URL VARCHAR(255) NOT NULL,
		SMALL_ICON_URL VARCHAR(255) NOT NULL,
		LARGE_ICON_URL VARCHAR(255) NOT NULL,
		PARENT_CATEGORY BIGINT NOT NULL,
		TAGS VARCHAR(500),
		MENU_ID BIGINT NOT NULL,
		AVAILABLE_DURATION_START TIME,
		AVAILABLE_DURATION_END TIME,
		RESTURANT_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(ITEM_CATEGORY_ID)
	);
	
	-- ITEM_VARIANT
	CREATE TABLE ITEM_VARIANT(
		ITEM_VARIANT_ID BIGINT NOT NULL AUTO_INCREMENT,
		ITEM_ID BIGINT NOT NULL,
		VARIANT_ID BIGINT NOT NULL,
		PRICE DECIMAL(5,3) NOT NULL,
		APPROX_PREPERATION_TIME INT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(ITEM_VARIANT_ID)
	);
	
	-- CUISINE_TYPE
	CREATE TABLE CUISINE_TYPE(
		CUISINE_TYPE_ID BIGINT NOT NULL AUTO_INCREMENT,
		IMAGE_URL VARCHAR(255) NOT NULL,
		RESTURANT_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		TITLE VARCHAR(255),
		PRIMARY KEY (CUISINE_TYPE_ID)
	);
	
	-- ITEM_DISCOUNT
	CREATE TABLE ITEM_DISCOUNT(
		ITEM_DISCOUNT_ID BIGINT NOT NULL AUTO_INCREMENT,
		DISCOUNT_PRICE DECIMAL(5,3) NOT NULL,
		START_DATE DATE NOT NULL,
		END_DATE DATE NOT NULL,
		ITEM_VARIANT_ID BIGINT,
		IS_ACTIVE INT(1),
		PRIMARY KEY(ITEM_DISCOUNT_ID)
	);
	
	-- ORDER_SPECIAL_DEAL_ITEM
	CREATE TABLE ORDER_SPECIAL_DEAL_ITEM(
		ORDER_SPECIAL_DEAL_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
		ORDER_ID BIGINT NOT NULL,
		QUANTITY INT NOT NULL,
		SPECIAL_REMARKS VARCHAR(255),
		ORDER_PRICE DECIMAL(5,3) NOT NULL,
		MEAL_DEAL_ITEM_ID BIGINT NOT NULL,
		PRIMARY KEY(ORDER_SPECIAL_DEAL_ITEM_ID)
	);
	
	-- SPECIAL_DEAL_ITEM
	CREATE TABLE SPECIAL_DEAL_ITEM(
		MEAL_DEAL_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
		SPECIAL_DEAL_ID BIGINT NOT NULL,
		ITEM_ID BIGINT NOT NULL,
		QUANTITY INT NOT NULL,
		PRIMARY KEY (MEAL_DEAL_ITEM_ID)
	);
	
	-- USER
	CREATE TABLE USERS(
		USER_ID BIGINT NOT NULL AUTO_INCREMENT,
		USERNAME VARCHAR(255) NOT NULL UNIQUE, 
		PASSWORD VARCHAR(255) NOT NULL,
		IS_LOCKED INT(1) DEFAULT 0,
		IS_ACTIVE INT(1),
		RESTURANT_ID BIGINT NOT NULL,
		PRIMARY KEY (USER_ID)
	);
	
	-- USER_ROLE
	CREATE TABLE USER_ROLE(
		USER_ROLE_ID BIGINT NOT NULL AUTO_INCREMENT,
		USER_ID BIGINT NOT NULL,
		ROLE_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY (USER_ROLE_ID)
	);
	
	-- ITEM_TRANSLATION
	CREATE TABLE ITEM_TRANSLATION(
		ITEM_TRANSLATION_ID BIGINT NOT NULL AUTO_INCREMENT,
		TITLE VARCHAR(255) NOT NULL,
		DESCRIPTION VARCHAR(255) NOT NULL,
		ITEM_ID BIGINT NOT NULL ,
		LANGUAGE_ID BIGINT NOT NULL,
		DIETARY_INFORMATION VARCHAR(255),
		IS_SPICY INT(1),
		SHOW_DESCRIPTION INT(1),
		PRIMARY KEY(ITEM_TRANSLATION_ID)
		
 	);
	
	--  MENU
	CREATE TABLE MENU(
		MENU_ID BIGINT NOT NULL AUTO_INCREMENT,
		TITLE VARCHAR(255) NOT NULL,
		RESTURANT_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY (MENU_ID)
	);
	
	--  ITEM
	CREATE TABLE ITEM(
		ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
		ITEM_CATEGORY_ID BIGINT NOT NULL,
		CUISINE_TYPE_ID BIGINT NOT NULL,
		SPICE_TYPE_ID BIGINT NOT NULL,
		PRICE DECIMAL(5,3) NOT NULL,
		TAGS VARCHAR(500),
		PRIMARY KEY (ITEM_ID)
	);
	
	-- INGREDIENTS
	CREATE TABLE INGREDIENTS(
		INGREDIENT_ID BIGINT NOT NULL AUTO_INCREMENT,
		IMAGE_URL VARCHAR(255) NOT NULL,
		IS_ACTIVE INT(1),
		RESTURANT_ID BIGINT NOT NULL,
		PRIMARY KEY(INGREDIENT_ID)
	);
	
	-- ITEM_MEDIA_CONTENT
	CREATE TABLE ITEM_MEDIA_CONTENT(
		ITEM_MEDIA_ID BIGINT NOT NULL AUTO_INCREMENT,
		ITEM_ID BIGINT NOT NULL,
		IMAGE_URL VARCHAR(255) NOT NULL,
		VEDIO_URL VARCHAR(255),
		VEDIO_SOURCE_ID BIGINT,
		DISPLAY_ORDER INT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(ITEM_MEDIA_ID)
	);
	
	--  ORDER_ITEM 
	CREATE TABLE ORDER_ITEMS(
		ORDER_ITEM BIGINT NOT NULL AUTO_INCREMENT,
		ORDER_ID BIGINT NOT NULL,
		ITEM_VARIANT_ID BIGINT NOT NULL,
		QUANTITY BIGINT NOT NULL,
		SPECIAL_REMARKS VARCHAR(500),
		ORDER_PRICE DECIMAL(5,3) NOT NULL,
		PRIMARY KEY(ORDER_ITEM)
	);
	
	-- SPECIAL_DEAL
	CREATE TABLE SPECIAL_DEAL(
		SPECIAL_DEAL_ID BIGINT NOT NULL AUTO_INCREMENT,
		START_DATE DATE NOT NULL,
		END_DATE DATE NOT NULL,
		PRICE DECIMAL(5,3) NOT NULL,
		IMAGE_URL VARCHAR(255),
		RESTURANT_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(SPECIAL_DEAL_ID)
	);
	
	-- STAFF
	CREATE TABLE STAFF(
		STAFF_ID BIGINT NOT NULL AUTO_INCREMENT,
		USER_ID BIGINT NOT NULL UNIQUE,
		STAFF_CODE VARCHAR(10) NOT NULL UNIQUE,
		FIRST_NAME VARCHAR(255) NOT NULL,
		MIDDLE_NAME VARCHAR(255),
		LAST_NAME VARCHAR(255) NOT NULL,
		ADDRESS_ID BIGINT NOT NULL,
		MOBILE_ID BIGINT,
		BRANCH_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(STAFF_ID)
	);
	
	-- ROLE_SERVICE
	CREATE TABLE ROLE_SERVICE(
		ROLE_SERVICE_ID BIGINT NOT NULL AUTO_INCREMENT,
		ROLE_ID BIGINT NOT NULL,
		SERVICE_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(ROLE_SERVICE_ID)
	);
	
	--  ROLE
	CREATE TABLE ROLE(
		ROLE_ID BIGINT NOT NULL AUTO_INCREMENT,
		ROLE_NAME VARCHAR(255) NOT NULL,
		DESCRIPTION VARCHAR(255) NOT NULL,
		RESTURANT_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY (ROLE_ID)
	);
	
	--  SERVING_TABLE
	CREATE TABLE SERVING_TABLE(
		SERVING_TABLE_ID BIGINT NOT NULL AUTO_INCREMENT,
		DESCRIPTION VARCHAR(255),
		TABLE_REF_NUMBER VARCHAR(10) NOT NULL,
		BRANCH_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(SERVING_TABLE_ID)
	);
	
	-- BRANCH
	CREATE TABLE BRANCH(
		BRANCH_ID BIGINT NOT NULL AUTO_INCREMENT,
		MANAGER_ID BIGINT NOT NULL,
		RESTURANT_ID BIGINT NOT NULL,
		ADDRESS_ID BIGINT NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY(BRANCH_ID)
	);
	
	-- ITEM_INGREDIENT
	CREATE TABLE ITEM_INGREDIENT(
		ITEM_INGREDIENT_ID BIGINT NOT NULL AUTO_INCREMENT,
		INGREDIENT_ID BIGINT NOT NULL,
		ITEM_ID BIGINT NOT NULL,
		PRIMARY KEY (ITEM_INGREDIENT_ID)
	);
	
	-- VEDIO_SOURCE_TYPE
	CREATE TABLE VEDIO_SOURCE_TYPE(
		VEDIO_SOURCE_ID BIGINT NOT NULL AUTO_INCREMENT,
		NAME VARCHAR(255) NOT NULL,
		DESCRIPTION VARCHAR(255) NOT NULL,
		IS_ACTIVE INT(1),
		PRIMARY KEY (VEDIO_SOURCE_ID)
	);
	
	--  CUSTOMER
	CREATE TABLE CUSTOMER(
		CUSTOMER_ID BIGINT NOT NULL AUTO_INCREMENT,
		CODE VARCHAR(10) NOT NULL UNIQUE,
		FIRST_NAME VARCHAR(255) NOT NULL,
		LAST_NAME VARCHAR(255),
		MOBILE VARCHAR(15),
		ADDRESS_ID BIGINT ,
		SUBSCRIBE_NEWS_LETTER INT(1),
		RESTURANT_ID BIGINT NOT NULL,
		PRIMARY KEY (CUSTOMER_ID)
	);
	
	--  FEEDBACK
	CREATE TABLE FEEDBACK(
		FEEDBACK_ID BIGINT NOT NULL AUTO_INCREMENT,
		RATING INT NOT NULL,
		REMARKS VARCHAR(255),
		ORDER_ID BIGINT NOT NULL,
		FEEDBACK_TYPE_ID BIGINT NOT NULL,
		BRANCH_ID BIGINT NOT NULL,
		PRIMARY KEY (FEEDBACK_ID)
	);
	
	--  RESTURANT
	CREATE TABLE RESTURANT (
    RESTURANT_ID BIGINT NOT NULL AUTO_INCREMENT,
    ACTIVATION_KEY VARCHAR(25) NOT NULL UNIQUE,
    CONTACT_PERSON VARCHAR(255) NOT NULL,
    LOGO_SMALL VARCHAR(255) NOT NULL,
    LOGO_LARGE VARCHAR(255) NOT NULL,
    THEME VARCHAR(5),
	ACCOUNT_TYPE_ID BIGINT NOT NULL,
    BACKGROUND_IMAGE VARCHAR(255),
    PRIMARY KEY (RESTURANT_ID)
);
	

--  SERVICE
CREATE TABLE SERVICE (
    SERVICE_ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	URL VARCHAR(255),
	IS_ACTIVE INT(1),
	RESTURANT_ID BIGINT NOT NULL,
    PRIMARY KEY (SERVICE_ID)
);
	
--  FEEDBACK_TYPE
	CREATE TABLE FEEDBACK_TYPE (
    FEEDBACK_TYPE_ID BIGINT NOT NULL AUTO_INCREMENT,
	IS_ACTIVE INT(1),
	RESTURANT_ID BIGINT NOT NULL,
    PRIMARY KEY (FEEDBACK_TYPE_ID)
);
	
--  ADDONS
	CREATE TABLE ADDONS (
    ADDON_ID BIGINT NOT NULL AUTO_INCREMENT,
	IS_ACTIVE INT(1),
	PRICE DECIMAL(5,3) NOT NULL,
	RESTURANT_ID BIGINT NOT NULL,
	IMAGE_URL VARCHAR(255),
    PRIMARY KEY (ADDON_ID)
);
	
--  ADDONS-TRANSLATION
	CREATE TABLE ADDON_TRANSLATION (
    ADDON_TRNASLATION_ID BIGINT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255),
	LANGUAGE_ID BIGINT NOT NULL,
	SHOW_DESCRIPTION INT(1),
    PRIMARY KEY (ADDON_TRNASLATION_ID)
);


--  ITEM - ADDONS
	CREATE TABLE ITEM_ADDON (
    ITEM_ADDON_ID BIGINT NOT NULL AUTO_INCREMENT,
	ADDON_ID BIGINT NOT NULL,
	PRICE DECIMAL(5,3) NOT NULL,
	IS_ACTIVE INT(1),
	ITEM_ID BIGINT NOT NULL,
    PRIMARY KEY (ITEM_ADDON_ID)
);

	
--  ORDER-ITEM-ADDON
	CREATE TABLE ORDER_ITEM_ADDON (
    ORDER_ITEM_ADDON_ID BIGINT NOT NULL AUTO_INCREMENT,
	ORDER_ID BIGINT NOT NULL,
	PRICE DECIMAL(5,3) NOT NULL,
	SPECIAL_REMARKS VARCHAR(500),
	QUANTITY INT(10) NOT NULL,
	ITEM_ADDON_ID BIGINT NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ADDON_ID)
);
	


--  ORDERS
	CREATE TABLE ORDERS (
    ORDER_ID BIGINT NOT NULL AUTO_INCREMENT,
	REFERENCE_NUM VARCHAR(255) NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	ORDER_DATE TIMESTAMP NOT NULL,
	SPECIAL_REMARKS VARCHAR(500),
	SERVING_TABLE_ID BIGINT NOT NULL,
	ORDER_STATUS BIGINT NOT NULL,
	CANCELLATION_REASON VARCHAR(500),
	DISCOUNT_APPLIED_PCT DECIMAL(5,3),
	STAFF_ID BIGINT NOT NULL,
	BRANCH_ID BIGINT NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

--  ORDERS
	CREATE TABLE ADDRESS (
    ADDRESS_ID BIGINT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	AREA VARCHAR(255),
	CITY VARCHAR(255),
	COUNTRY VARCHAR(50),
	PO_BOX VARCHAR(15),
	TEL1 VARCHAR(20),
	TEL2 VARCHAR(20),
	TEL3 VARCHAR(20),
	TEL4 VARCHAR(20),
	LAT VARCHAR(25),
	LONGITUDE VARCHAR(25),
	IS_ACTIVE INT(1),
	EMAIL VARCHAR(50),
    PRIMARY KEY (ADDRESS_ID)
);
				
	
-- CONSTRAINTS

ALTER TABLE OBJECT_JSON ADD CONSTRAINT FK_JSON_LNG FOREIGN KEY (LANGUAGE_ID) REFERENCES REF_LANGUAGES(LANGUAGE_ID); 
ALTER TABLE OBJECT_JSON ADD CONSTRAINT FK_JSON_REST FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);
; 



ALTER TABLE ITEM_CATEGORY_TRANSLATION ADD CONSTRAINT FK_ICT_LNG FOREIGN KEY (LANGUAGE_ID) REFERENCES REF_LANGUAGES(LANGUAGE_ID); 

ALTER TABLE ITEM_CATEGORY_TRANSLATION ADD CONSTRAINT FK_ICT_MC FOREIGN KEY (MENU_CATEGORY_ID) REFERENCES ITEM_CATEGORY(ITEM_CATEGORY_ID); 

ALTER TABLE INGREDIENT_TRANSLATION
ADD CONSTRAINT FK_INGTRA_ING 
FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS(INGREDIENT_ID);

ALTER TABLE INGREDIENT_TRANSLATION
ADD CONSTRAINT FK_INGTRA_LNG
FOREIGN KEY(LANGUAGE_ID) 
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE SPICE_TYPE_TRANSLATION
ADD CONSTRAINT FK_SPT_LNG 
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE SPICE_TYPE_TRANSLATION
ADD CONSTRAINT FK_SPT_SPI
FOREIGN KEY (SPICE_TYPE_ID)
REFERENCES SPICE_TYPE(SPICE_TYPE_ID);

ALTER TABLE SPICE_TYPE
ADD CONSTRAINT FK_SPT_RST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE RESTURANT_LANGUAGE
ADD CONSTRAINT FK_RST_LNG
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE RESTURANT_LANGUAGE 
ADD CONSTRAINT FK_RSTLNG_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE SPECIAL_DEAL_TRANSLATION
ADD CONSTRAINT FK_SMT_LNG
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE SPECIAL_DEAL_TRANSLATION
ADD CONSTRAINT FK_SMT_SPD
FOREIGN KEY (SPECIAL_DEAL_ID)
REFERENCES SPECIAL_DEAL(SPECIAL_DEAL_ID);

ALTER TABLE RESTURANT_TRANSLATION
ADD CONSTRAINT FK_RESTTR_LNG 
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE RESTURANT_TRANSLATION
ADD CONSTRAINT FK_RESTTR_REST
FOREIGN KEY (RESTURANT_ID) 
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE VARIANT_TRANSLATION
ADD CONSTRAINT FK_VARTRA_LNG
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);	
	
ALTER TABLE VARIANT_TRANSLATION
ADD CONSTRAINT FK_VARTRA_VAR
FOREIGN KEY (VARIANT_ID)
REFERENCES VARIANT(VARIANT_ID);

ALTER TABLE VARIANT
ADD CONSTRAINT FK_VAR_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE CUISINE_TRANSLATION 
ADD CONSTRAINT FK_CUSTRA_LNG
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE CUISINE_TRANSLATION 
ADD CONSTRAINT FK_CUSTRA_CUS
FOREIGN KEY (CUISINE_TYPE_ID)
REFERENCES CUISINE_TYPE(CUISINE_TYPE_ID);

ALTER TABLE FEEDBACK_TRANSLATION
ADD CONSTRAINT FK_FBT_LNG
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE FEEDBACK_TRANSLATION
ADD CONSTRAINT FK_FBT_FB
FOREIGN KEY (FEEDBACK_TYPE_ID)
REFERENCES FEEDBACK(FEEDBACK_ID);

ALTER TABLE ITEM_TRANSLATION
ADD CONSTRAINT FK_ITTR_LNG
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE ITEM_TRANSLATION
ADD CONSTRAINT FK_ITTR_IT
FOREIGN KEY (ITEM_ID)
REFERENCES ITEM(ITEM_ID);

ALTER TABLE MENU
ADD CONSTRAINT FK_MENU_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE ITEM 
ADD CONSTRAINT FK_ITEM_CAT
FOREIGN KEY (ITEM_CATEGORY_ID)
REFERENCES ITEM_CATEGORY(ITEM_CATEGORY_ID);

ALTER TABLE ITEM
ADD CONSTRAINT FK_ITEM_CT
FOREIGN KEY (CUISINE_TYPE_ID)
REFERENCES CUISINE_TYPE(CUISINE_TYPE_ID);

ALTER TABLE ITEM 
ADD CONSTRAINT FK_ITEM_SPICE
FOREIGN KEY (SPICE_TYPE_ID)
REFERENCES SPICE_TYPE(SPICE_TYPE_ID);

ALTER TABLE INGREDIENTS
ADD CONSTRAINT FK_ING_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE ITEM_MEDIA_CONTENT
ADD CONSTRAINT FK_IMC_IT
FOREIGN KEY (ITEM_ID)
REFERENCES ITEM(ITEM_ID);

ALTER TABLE ITEM_MEDIA_CONTENT
ADD CONSTRAINT FK_IMC_VS
FOREIGN KEY (VEDIO_SOURCE_ID)
REFERENCES VEDIO_SOURCE_TYPE(VEDIO_SOURCE_ID);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT FK_OI_IV
FOREIGN KEY (ITEM_VARIANT_ID)
REFERENCES ITEM_VARIANT(ITEM_VARIANT_ID);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT FK_OI_ORD
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);

ALTER TABLE SPECIAL_DEAL
ADD CONSTRAINT FK_SD_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE CUISINE_TYPE
ADD CONSTRAINT FK_CT_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE ITEM_DISCOUNT
ADD CONSTRAINT FK_ITDIS_VAR
FOREIGN KEY (ITEM_VARIANT_ID)
REFERENCES ITEM_VARIANT(ITEM_VARIANT_ID);

ALTER TABLE ORDER_SPECIAL_DEAL_ITEM
ADD CONSTRAINT FK_OSDI_ORD
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);

ALTER TABLE ORDER_SPECIAL_DEAL_ITEM
ADD CONSTRAINT FK_OSDI_MDI
FOREIGN KEY (MEAL_DEAL_ITEM_ID)
REFERENCES SPECIAL_DEAL_ITEM (MEAL_DEAL_ITEM_ID);

ALTER TABLE SPECIAL_DEAL_ITEM
ADD CONSTRAINT FK_SDI_SD
FOREIGN KEY (SPECIAL_DEAL_ID)
REFERENCES SPECIAL_DEAL(SPECIAL_DEAL_ID);

ALTER TABLE SPECIAL_DEAL_ITEM
ADD CONSTRAINT FK_SDI_ITM
FOREIGN KEY (ITEM_ID)
REFERENCES ITEM(ITEM_ID);

ALTER TABLE USERS
ADD CONSTRAINT FK_USR_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE STAFF
ADD CONSTRAINT FK_STAFF_USER
FOREIGN KEY (USER_ID)
REFERENCES USERS(USER_ID);

ALTER TABLE STAFF
ADD CONSTRAINT FK_STAFF_ADD
FOREIGN KEY (ADDRESS_ID)
REFERENCES ADDRESS(ADDRESS_ID);

ALTER TABLE STAFF
ADD CONSTRAINT FK_STAFF_BRN
FOREIGN KEY (BRANCH_ID)
REFERENCES BRANCH(BRANCH_ID);

ALTER TABLE USER_ROLE
ADD CONSTRAINT FK_USR_ROL
FOREIGN KEY (USER_ID)
REFERENCES USERS(USER_ID);

ALTER TABLE USER_ROLE
ADD CONSTRAINT FK_USR_USER
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE(ROLE_ID);

ALTER TABLE ROLE_SERVICE
ADD CONSTRAINT FK_RS_ROLE
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE(ROLE_ID);

ALTER TABLE ROLE_SERVICE
ADD CONSTRAINT FK_RS_SERV
FOREIGN KEY (SERVICE_ID)
REFERENCES SERVICE(SERVICE_ID);

ALTER TABLE SERVICE
ADD CONSTRAINT FK_SER_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE ROLE
ADD CONSTRAINT FK_ROLE_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE SERVING_TABLE
ADD CONSTRAINT FK_ST_BR
FOREIGN KEY (BRANCH_ID)
REFERENCES BRANCH(BRANCH_ID);

ALTER TABLE BRANCH
ADD CONSTRAINT FK_BR_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE BRANCH 
ADD CONSTRAINT FK_BR_ADD
FOREIGN KEY (ADDRESS_ID)
REFERENCES ADDRESS(ADDRESS_ID);

ALTER TABLE ITEM_INGREDIENT
ADD CONSTRAINT FK_II_ITEM
FOREIGN KEY (ITEM_ID)
REFERENCES ITEM(ITEM_ID);

ALTER TABLE ITEM_INGREDIENT
ADD CONSTRAINT FK_II_ING
FOREIGN KEY (INGREDIENT_ID)
REFERENCES INGREDIENTS(INGREDIENT_ID);

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUST_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORD_CUST
FOREIGN KEY (CUSTOMER_ID)
REFERENCES  CUSTOMER(CUSTOMER_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORD_ST
FOREIGN KEY (SERVING_TABLE_ID)
REFERENCES  SERVING_TABLE(SERVING_TABLE_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORD_STF
FOREIGN KEY (STAFF_ID)
REFERENCES  STAFF(STAFF_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORD_BR
FOREIGN KEY (BRANCH_ID)
REFERENCES  BRANCH(BRANCH_ID);

ALTER TABLE FEEDBACK
ADD CONSTRAINT FK_FB_ORD
FOREIGN KEY (ORDER_ID)
REFERENCES  ORDERS(ORDER_ID);

ALTER TABLE FEEDBACK
ADD CONSTRAINT FK_FB_TYP
FOREIGN KEY (FEEDBACK_TYPE_ID)
REFERENCES  FEEDBACK_TYPE(FEEDBACK_TYPE_ID);

ALTER TABLE FEEDBACK
ADD CONSTRAINT FK_FB_BR
FOREIGN KEY (BRANCH_ID)
REFERENCES  BRANCH(BRANCH_ID);

ALTER TABLE ADDON_TRANSLATION 
ADD CONSTRAINT FK_ADDONTRA_LAN
FOREIGN KEY (LANGUAGE_ID)
REFERENCES REF_LANGUAGES(LANGUAGE_ID);

ALTER TABLE ADDONS
ADD CONSTRAINT FK_ADDON_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

ALTER TABLE ITEM_ADDON 
ADD CONSTRAINT FK_ITEMADDON_ITEM
FOREIGN KEY (ITEM_ID)
REFERENCES ITEM(ITEM_ID);

ALTER TABLE ITEM_ADDON 
ADD CONSTRAINT FK_ITEMADDON_ADDON
FOREIGN KEY (ADDON_ID)
REFERENCES ADDONS(ADDON_ID);

ALTER TABLE ORDER_ITEM_ADDON 
ADD CONSTRAINT FK_OIA_IAD
FOREIGN KEY (ITEM_ADDON_ID)
REFERENCES ITEM_ADDON(ITEM_ID);

ALTER TABLE ORDER_ITEM_ADDON 
ADD CONSTRAINT FK_OIA_ORD
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);


ALTER TABLE RESTURANT 
ADD CONSTRAINT FK_REST_ACCT
FOREIGN KEY (ACCOUNT_TYPE_ID)
REFERENCES ACCOUNT_TYPE(ACCOUNT_TYPE_ID);

ALTER TABLE RESTAURANT_DEVICE 
ADD CONSTRAINT FK_RESTD_REST
FOREIGN KEY (RESTURANT_ID)
REFERENCES RESTURANT(RESTURANT_ID);

--- UNIQUE CONSTRAINTS

ALTER TABLE ITEM_CATEGORY_TRANSLATION
ADD UNIQUE UNQ_ICT(LANGUAGE_ID, MENU_CATEGORY_ID);

ALTER TABLE INGREDIENT_TRANSLATION
ADD UNIQUE UNQ_INGTRAN(INGREDIENT_ID,LANGUAGE_ID);

ALTER TABLE SPICE_TYPE_TRANSLATION
ADD UNIQUE UNQ_STT (LANGUAGE_ID,SPICE_TYPE_ID);

ALTER TABLE RESTURANT_LANGUAGE
ADD UNIQUE UNQ_RESTLANG(RESTURANT_ID,LANGUAGE_ID);

ALTER TABLE ITEM_ADDON
ADD UNIQUE UNQ_ITMAO (ITEM_ID , ADDON_ID);

ALTER TABLE SPECIAL_DEAL_TRANSLATION 
ADD UNIQUE UNQ_SDT(SPECIAL_DEAL_ID, LANGUAGE_ID);

ALTER TABLE RESTURANT_TRANSLATION
ADD UNIQUE UNQ_RESTTRA(RESTURANT_ID,LANGUAGE_ID);

ALTER TABLE VARIANT_TRANSLATION
ADD UNIQUE UNQ_VARTRA(VARIANT_ID,LANGUAGE_ID);

ALTER TABLE CUISINE_TRANSLATION
ADD UNIQUE UNQ_CUSTRA(CUISINE_TYPE_ID,LANGUAGE_ID);

ALTER TABLE FEEDBACK_TRANSLATION
ADD UNIQUE UNQ_FBTRA (FEEDBACK_TYPE_ID,LANGUAGE_ID);

ALTER TABLE ITEM_TRANSLATION
ADD UNIQUE UNQ_ITTRA(ITEM_ID,LANGUAGE_ID);

ALTER TABLE ITEM_CATEGORY
ADD UNIQUE UNQ_ITECAT(RESTURANT_ID, MENU_ID);

ALTER TABLE ITEM_VARIANT
ADD UNIQUE UNQ_ITMVAR(ITEM_ID, VARIANT_ID);

ALTER TABLE USER_ROLE 
ADD UNIQUE UNQ_USRROLE(USER_ID,ROLE_ID);

ALTER TABLE ROLE_SERVICE
ADD UNIQUE UNQ_RLSER(ROLE_ID, SERVICE_ID);

ALTER TABLE ITEM
ADD UNIQUE UNQ_ITM(ITEM_CATEGORY_ID,CUISINE_TYPE_ID,SPICE_TYPE_ID);

