CREATE TABLE `xxxx_translation` (
  `xxxx_TRANSLATION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `xxxx_ID` bigint(20) NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `LANGUAGE_ID` bigint(20) NOT NULL,
  `SHOW_DESCRIPTION` int(1) DEFAULT 0,
  PRIMARY KEY (`xxxx_TRANSLATION_ID`),
  UNIQUE KEY `UK_xxxx_TR` (`FEEDBACK_CONFIG_ID`,`LANGUAGE_ID`),
  CONSTRAINT `FK_xxxx_TR` FOREIGN KEY (`xxxx_ID`) REFERENCES `xxxx` (`xxxx_id`),
  CONSTRAINT `FK_FEEDBKCONF_LANG` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `ref_languages` (`language_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


ALTER TABLE `USERS` 
ADD COLUMN `DATE_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `CREATED_BY` BIGINT(20) NOT NULL,
ADD COLUMN `LAST_UPDATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `UPDATED_BY` BIGINT(20) NULL,
ADD COLUMN `ACTION_TYPE` VARCHAR(50) NULL
;

CREATE TABLE `feedback_customer` (
  `FEEDBACK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` bigint(20),
  `CUSTOMER_CONTACT` varchar(255),
  `FEEDBACK_CONFIG_ID` bigint(20),
  `VALUE` varchar(255),
  `FEEDBACK_CONTEXT` varchar(20),
  `REFERENCE_ID` bigint(20),
  PRIMARY KEY (`FEEDBACK_ID`),
  CONSTRAINT `FK_FEEDBK_CUSTID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer` (`customer_id`),
  CONSTRAINT `FK_FEEDBK_FEEDBK_CONF` FOREIGN KEY (`FEEDBACK_CONFIG_ID`) REFERENCES `feedback_config` (`feedback_config_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


SET FOREIGN_KEY_CHECKS=1;

ALTER TABLE `restaurant`.`staff` 
ADD CONSTRAINT `FK_STAFF_REST`
  FOREIGN KEY (`RESTAURANT_ID`)
  REFERENCES `restaurant`.`restaurant` (`RESTAURANT_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `restaurant`.`serving_table` 
ADD CONSTRAINT `FK_SERV_TBL_REST`
  FOREIGN KEY (`RESTAURANT_ID`)
  REFERENCES `restaurant`.`restaurant` (`RESTAURANT_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `restaurant`.`order` 
ADD CONSTRAINT `FK_ORD_STATUS`
  FOREIGN KEY (`STATUS_TYPE_ID`)
  REFERENCES `restaurant`.`status_type` (`STATUS_TYPE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `restaurant`.`order` 
ADD CONSTRAINT `FK_ORD_REST`
  FOREIGN KEY (`RESTAURANT_ID`)
  REFERENCES `restaurant`.`restaurant` (`RESTAURANT_ID`)
  ON DELETE RESTRICT
  ON UPDATE NO ACTION;

ALTER TABLE `restaurant`.`addon_translation` 
CHANGE COLUMN `SHOW_DESCRIPTION` `SHOW_DESCRIPTION` BIT(1) NULL DEFAULT 0 ,
ADD COLUMN `IS_DEFAULT` BIT(1) NULL AFTER `VERSION`;


ALTER TABLE `restaurant`.`addon_translation` 
ADD UNIQUE INDEX `UK_ADDON_TRANS_LANG` (`LANGUAGE_ID` ASC, `ADDON_ID` ASC);
