hibernate.format_sql=false
hibernate.show_sql=true
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.driver=com.mysql.jdbc.Driver
hiberante.username=${db.username}
hibernate.password=${db.password}
hibernate.db.url=jdbc:mysql://localhost:3306/resturant

login.invalid.credentials = Invalid Login credentials.
message.norecordfound = No Record Found.